/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ContactCreatedResponseDto } from '../models';
// @ts-ignore
import type { ContactResponseDto } from '../models';
// @ts-ignore
import type { CreateContactDto } from '../models';
// @ts-ignore
import type { MessageResponseDto } from '../models';
// @ts-ignore
import type { UpdateContactDto } from '../models';
/**
 * ContactsApi - axios parameter creator
 * @export
 */
export const ContactsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new contact
         * @param {CreateContactDto} createContactDto Data to create a new contact.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsControllerCreate: async (createContactDto: CreateContactDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createContactDto' is not null or undefined
            assertParamExists('contactsControllerCreate', 'createContactDto', createContactDto)
            const localVarPath = `/api/contacts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createContactDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all contacts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/contacts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a single contact
         * @param {string} id Contact ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contactsControllerFindOne', 'id', id)
            const localVarPath = `/api/contacts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a contact by its ID
         * @param {string} id Contact ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contactsControllerRemove', 'id', id)
            const localVarPath = `/api/contacts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a contact
         * @param {string} id ID of the contact to update
         * @param {UpdateContactDto} updateContactDto New data for the contact.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsControllerUpdate: async (id: string, updateContactDto: UpdateContactDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contactsControllerUpdate', 'id', id)
            // verify required parameter 'updateContactDto' is not null or undefined
            assertParamExists('contactsControllerUpdate', 'updateContactDto', updateContactDto)
            const localVarPath = `/api/contacts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateContactDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContactsApi - functional programming interface
 * @export
 */
export const ContactsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContactsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new contact
         * @param {CreateContactDto} createContactDto Data to create a new contact.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactsControllerCreate(createContactDto: CreateContactDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactsControllerCreate(createContactDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactsApi.contactsControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all contacts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactsControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ContactResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactsControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactsApi.contactsControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a single contact
         * @param {string} id Contact ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactsControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactsControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactsApi.contactsControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a contact by its ID
         * @param {string} id Contact ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactsControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactsControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactsApi.contactsControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a contact
         * @param {string} id ID of the contact to update
         * @param {UpdateContactDto} updateContactDto New data for the contact.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactsControllerUpdate(id: string, updateContactDto: UpdateContactDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactsControllerUpdate(id, updateContactDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactsApi.contactsControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ContactsApi - factory interface
 * @export
 */
export const ContactsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContactsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new contact
         * @param {ContactsApiContactsControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsControllerCreate(requestParameters: ContactsApiContactsControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactCreatedResponseDto> {
            return localVarFp.contactsControllerCreate(requestParameters.createContactDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all contacts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<ContactResponseDto>> {
            return localVarFp.contactsControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a single contact
         * @param {ContactsApiContactsControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsControllerFindOne(requestParameters: ContactsApiContactsControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactResponseDto> {
            return localVarFp.contactsControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a contact by its ID
         * @param {ContactsApiContactsControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsControllerRemove(requestParameters: ContactsApiContactsControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto> {
            return localVarFp.contactsControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a contact
         * @param {ContactsApiContactsControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsControllerUpdate(requestParameters: ContactsApiContactsControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactCreatedResponseDto> {
            return localVarFp.contactsControllerUpdate(requestParameters.id, requestParameters.updateContactDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ContactsApi - interface
 * @export
 * @interface ContactsApi
 */
export interface ContactsApiInterface {
    /**
     * 
     * @summary Create a new contact
     * @param {ContactsApiContactsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    contactsControllerCreate(requestParameters: ContactsApiContactsControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactCreatedResponseDto>;

    /**
     * 
     * @summary Get all contacts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    contactsControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<ContactResponseDto>>;

    /**
     * 
     * @summary Get a single contact
     * @param {ContactsApiContactsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    contactsControllerFindOne(requestParameters: ContactsApiContactsControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactResponseDto>;

    /**
     * 
     * @summary Delete a contact by its ID
     * @param {ContactsApiContactsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    contactsControllerRemove(requestParameters: ContactsApiContactsControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto>;

    /**
     * 
     * @summary Update a contact
     * @param {ContactsApiContactsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    contactsControllerUpdate(requestParameters: ContactsApiContactsControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactCreatedResponseDto>;

}

/**
 * Request parameters for contactsControllerCreate operation in ContactsApi.
 * @export
 * @interface ContactsApiContactsControllerCreateRequest
 */
export interface ContactsApiContactsControllerCreateRequest {
    /**
     * Data to create a new contact.
     * @type {CreateContactDto}
     * @memberof ContactsApiContactsControllerCreate
     */
    readonly createContactDto: CreateContactDto
}

/**
 * Request parameters for contactsControllerFindOne operation in ContactsApi.
 * @export
 * @interface ContactsApiContactsControllerFindOneRequest
 */
export interface ContactsApiContactsControllerFindOneRequest {
    /**
     * Contact ID
     * @type {string}
     * @memberof ContactsApiContactsControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for contactsControllerRemove operation in ContactsApi.
 * @export
 * @interface ContactsApiContactsControllerRemoveRequest
 */
export interface ContactsApiContactsControllerRemoveRequest {
    /**
     * Contact ID
     * @type {string}
     * @memberof ContactsApiContactsControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for contactsControllerUpdate operation in ContactsApi.
 * @export
 * @interface ContactsApiContactsControllerUpdateRequest
 */
export interface ContactsApiContactsControllerUpdateRequest {
    /**
     * ID of the contact to update
     * @type {string}
     * @memberof ContactsApiContactsControllerUpdate
     */
    readonly id: string

    /**
     * New data for the contact.
     * @type {UpdateContactDto}
     * @memberof ContactsApiContactsControllerUpdate
     */
    readonly updateContactDto: UpdateContactDto
}

/**
 * ContactsApi - object-oriented interface
 * @export
 * @class ContactsApi
 * @extends {BaseAPI}
 */
export class ContactsApi extends BaseAPI implements ContactsApiInterface {
    /**
     * 
     * @summary Create a new contact
     * @param {ContactsApiContactsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApi
     */
    public contactsControllerCreate(requestParameters: ContactsApiContactsControllerCreateRequest, options?: RawAxiosRequestConfig) {
        return ContactsApiFp(this.configuration).contactsControllerCreate(requestParameters.createContactDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all contacts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApi
     */
    public contactsControllerFindAll(options?: RawAxiosRequestConfig) {
        return ContactsApiFp(this.configuration).contactsControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a single contact
     * @param {ContactsApiContactsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApi
     */
    public contactsControllerFindOne(requestParameters: ContactsApiContactsControllerFindOneRequest, options?: RawAxiosRequestConfig) {
        return ContactsApiFp(this.configuration).contactsControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a contact by its ID
     * @param {ContactsApiContactsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApi
     */
    public contactsControllerRemove(requestParameters: ContactsApiContactsControllerRemoveRequest, options?: RawAxiosRequestConfig) {
        return ContactsApiFp(this.configuration).contactsControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a contact
     * @param {ContactsApiContactsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApi
     */
    public contactsControllerUpdate(requestParameters: ContactsApiContactsControllerUpdateRequest, options?: RawAxiosRequestConfig) {
        return ContactsApiFp(this.configuration).contactsControllerUpdate(requestParameters.id, requestParameters.updateContactDto, options).then((request) => request(this.axios, this.basePath));
    }
}

