/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateInvalidTokenDto } from '../models';
// @ts-ignore
import type { InvalidTokenCreatedResponseDto } from '../models';
// @ts-ignore
import type { InvalidTokenResponseDto } from '../models';
// @ts-ignore
import type { MessageResponseDto } from '../models';
// @ts-ignore
import type { UpdateInvalidTokenDto } from '../models';
/**
 * InvalidTokensApi - axios parameter creator
 * @export
 */
export const InvalidTokensApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Revoke a token
         * @param {CreateInvalidTokenDto} createInvalidTokenDto Data to add a token to the denylist.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerCreate: async (createInvalidTokenDto: CreateInvalidTokenDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createInvalidTokenDto' is not null or undefined
            assertParamExists('invalidTokensControllerCreate', 'createInvalidTokenDto', createInvalidTokenDto)
            const localVarPath = `/api/invalid-tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createInvalidTokenDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all denylist entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/invalid-tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a single denylist entry
         * @param {string} id Denylist entry ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('invalidTokensControllerFindOne', 'id', id)
            const localVarPath = `/api/invalid-tokens/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Removes entries past their expiry. Safe because ordinary JWT validation rejects an expired token anyway.
         * @summary Purge expired denylist entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerPurgeExpired: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/invalid-tokens/expired`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a denylist entry by its ID
         * @param {string} id Denylist entry ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('invalidTokensControllerRemove', 'id', id)
            const localVarPath = `/api/invalid-tokens/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a denylist entry
         * @param {string} id ID of the entry to update
         * @param {UpdateInvalidTokenDto} updateInvalidTokenDto New data for the denylist entry.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerUpdate: async (id: string, updateInvalidTokenDto: UpdateInvalidTokenDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('invalidTokensControllerUpdate', 'id', id)
            // verify required parameter 'updateInvalidTokenDto' is not null or undefined
            assertParamExists('invalidTokensControllerUpdate', 'updateInvalidTokenDto', updateInvalidTokenDto)
            const localVarPath = `/api/invalid-tokens/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateInvalidTokenDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvalidTokensApi - functional programming interface
 * @export
 */
export const InvalidTokensApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InvalidTokensApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Revoke a token
         * @param {CreateInvalidTokenDto} createInvalidTokenDto Data to add a token to the denylist.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invalidTokensControllerCreate(createInvalidTokenDto: CreateInvalidTokenDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InvalidTokenCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.invalidTokensControllerCreate(createInvalidTokenDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvalidTokensApi.invalidTokensControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all denylist entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invalidTokensControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InvalidTokenResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.invalidTokensControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvalidTokensApi.invalidTokensControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a single denylist entry
         * @param {string} id Denylist entry ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invalidTokensControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InvalidTokenResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.invalidTokensControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvalidTokensApi.invalidTokensControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Removes entries past their expiry. Safe because ordinary JWT validation rejects an expired token anyway.
         * @summary Purge expired denylist entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invalidTokensControllerPurgeExpired(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.invalidTokensControllerPurgeExpired(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvalidTokensApi.invalidTokensControllerPurgeExpired']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a denylist entry by its ID
         * @param {string} id Denylist entry ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invalidTokensControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.invalidTokensControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvalidTokensApi.invalidTokensControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a denylist entry
         * @param {string} id ID of the entry to update
         * @param {UpdateInvalidTokenDto} updateInvalidTokenDto New data for the denylist entry.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invalidTokensControllerUpdate(id: string, updateInvalidTokenDto: UpdateInvalidTokenDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InvalidTokenCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.invalidTokensControllerUpdate(id, updateInvalidTokenDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvalidTokensApi.invalidTokensControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InvalidTokensApi - factory interface
 * @export
 */
export const InvalidTokensApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InvalidTokensApiFp(configuration)
    return {
        /**
         * 
         * @summary Revoke a token
         * @param {InvalidTokensApiInvalidTokensControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerCreate(requestParameters: InvalidTokensApiInvalidTokensControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<InvalidTokenCreatedResponseDto> {
            return localVarFp.invalidTokensControllerCreate(requestParameters.createInvalidTokenDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all denylist entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<InvalidTokenResponseDto>> {
            return localVarFp.invalidTokensControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a single denylist entry
         * @param {InvalidTokensApiInvalidTokensControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerFindOne(requestParameters: InvalidTokensApiInvalidTokensControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<InvalidTokenResponseDto> {
            return localVarFp.invalidTokensControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Removes entries past their expiry. Safe because ordinary JWT validation rejects an expired token anyway.
         * @summary Purge expired denylist entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerPurgeExpired(options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto> {
            return localVarFp.invalidTokensControllerPurgeExpired(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a denylist entry by its ID
         * @param {InvalidTokensApiInvalidTokensControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerRemove(requestParameters: InvalidTokensApiInvalidTokensControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto> {
            return localVarFp.invalidTokensControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a denylist entry
         * @param {InvalidTokensApiInvalidTokensControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidTokensControllerUpdate(requestParameters: InvalidTokensApiInvalidTokensControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<InvalidTokenCreatedResponseDto> {
            return localVarFp.invalidTokensControllerUpdate(requestParameters.id, requestParameters.updateInvalidTokenDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InvalidTokensApi - interface
 * @export
 * @interface InvalidTokensApi
 */
export interface InvalidTokensApiInterface {
    /**
     * 
     * @summary Revoke a token
     * @param {InvalidTokensApiInvalidTokensControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApiInterface
     */
    invalidTokensControllerCreate(requestParameters: InvalidTokensApiInvalidTokensControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<InvalidTokenCreatedResponseDto>;

    /**
     * 
     * @summary Get all denylist entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApiInterface
     */
    invalidTokensControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<InvalidTokenResponseDto>>;

    /**
     * 
     * @summary Get a single denylist entry
     * @param {InvalidTokensApiInvalidTokensControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApiInterface
     */
    invalidTokensControllerFindOne(requestParameters: InvalidTokensApiInvalidTokensControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<InvalidTokenResponseDto>;

    /**
     * Removes entries past their expiry. Safe because ordinary JWT validation rejects an expired token anyway.
     * @summary Purge expired denylist entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApiInterface
     */
    invalidTokensControllerPurgeExpired(options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto>;

    /**
     * 
     * @summary Delete a denylist entry by its ID
     * @param {InvalidTokensApiInvalidTokensControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApiInterface
     */
    invalidTokensControllerRemove(requestParameters: InvalidTokensApiInvalidTokensControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto>;

    /**
     * 
     * @summary Update a denylist entry
     * @param {InvalidTokensApiInvalidTokensControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApiInterface
     */
    invalidTokensControllerUpdate(requestParameters: InvalidTokensApiInvalidTokensControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<InvalidTokenCreatedResponseDto>;

}

/**
 * Request parameters for invalidTokensControllerCreate operation in InvalidTokensApi.
 * @export
 * @interface InvalidTokensApiInvalidTokensControllerCreateRequest
 */
export interface InvalidTokensApiInvalidTokensControllerCreateRequest {
    /**
     * Data to add a token to the denylist.
     * @type {CreateInvalidTokenDto}
     * @memberof InvalidTokensApiInvalidTokensControllerCreate
     */
    readonly createInvalidTokenDto: CreateInvalidTokenDto
}

/**
 * Request parameters for invalidTokensControllerFindOne operation in InvalidTokensApi.
 * @export
 * @interface InvalidTokensApiInvalidTokensControllerFindOneRequest
 */
export interface InvalidTokensApiInvalidTokensControllerFindOneRequest {
    /**
     * Denylist entry ID
     * @type {string}
     * @memberof InvalidTokensApiInvalidTokensControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for invalidTokensControllerRemove operation in InvalidTokensApi.
 * @export
 * @interface InvalidTokensApiInvalidTokensControllerRemoveRequest
 */
export interface InvalidTokensApiInvalidTokensControllerRemoveRequest {
    /**
     * Denylist entry ID
     * @type {string}
     * @memberof InvalidTokensApiInvalidTokensControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for invalidTokensControllerUpdate operation in InvalidTokensApi.
 * @export
 * @interface InvalidTokensApiInvalidTokensControllerUpdateRequest
 */
export interface InvalidTokensApiInvalidTokensControllerUpdateRequest {
    /**
     * ID of the entry to update
     * @type {string}
     * @memberof InvalidTokensApiInvalidTokensControllerUpdate
     */
    readonly id: string

    /**
     * New data for the denylist entry.
     * @type {UpdateInvalidTokenDto}
     * @memberof InvalidTokensApiInvalidTokensControllerUpdate
     */
    readonly updateInvalidTokenDto: UpdateInvalidTokenDto
}

/**
 * InvalidTokensApi - object-oriented interface
 * @export
 * @class InvalidTokensApi
 * @extends {BaseAPI}
 */
export class InvalidTokensApi extends BaseAPI implements InvalidTokensApiInterface {
    /**
     * 
     * @summary Revoke a token
     * @param {InvalidTokensApiInvalidTokensControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApi
     */
    public invalidTokensControllerCreate(requestParameters: InvalidTokensApiInvalidTokensControllerCreateRequest, options?: RawAxiosRequestConfig) {
        return InvalidTokensApiFp(this.configuration).invalidTokensControllerCreate(requestParameters.createInvalidTokenDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all denylist entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApi
     */
    public invalidTokensControllerFindAll(options?: RawAxiosRequestConfig) {
        return InvalidTokensApiFp(this.configuration).invalidTokensControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a single denylist entry
     * @param {InvalidTokensApiInvalidTokensControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApi
     */
    public invalidTokensControllerFindOne(requestParameters: InvalidTokensApiInvalidTokensControllerFindOneRequest, options?: RawAxiosRequestConfig) {
        return InvalidTokensApiFp(this.configuration).invalidTokensControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Removes entries past their expiry. Safe because ordinary JWT validation rejects an expired token anyway.
     * @summary Purge expired denylist entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApi
     */
    public invalidTokensControllerPurgeExpired(options?: RawAxiosRequestConfig) {
        return InvalidTokensApiFp(this.configuration).invalidTokensControllerPurgeExpired(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a denylist entry by its ID
     * @param {InvalidTokensApiInvalidTokensControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApi
     */
    public invalidTokensControllerRemove(requestParameters: InvalidTokensApiInvalidTokensControllerRemoveRequest, options?: RawAxiosRequestConfig) {
        return InvalidTokensApiFp(this.configuration).invalidTokensControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a denylist entry
     * @param {InvalidTokensApiInvalidTokensControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvalidTokensApi
     */
    public invalidTokensControllerUpdate(requestParameters: InvalidTokensApiInvalidTokensControllerUpdateRequest, options?: RawAxiosRequestConfig) {
        return InvalidTokensApiFp(this.configuration).invalidTokensControllerUpdate(requestParameters.id, requestParameters.updateInvalidTokenDto, options).then((request) => request(this.axios, this.basePath));
    }
}

