/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateInventoryItemDto } from '../models';
// @ts-ignore
import type { DonationReason } from '../models';
// @ts-ignore
import type { InventoryFacetsResponseDto } from '../models';
// @ts-ignore
import type { InventoryItemCreatedResponseDto } from '../models';
// @ts-ignore
import type { InventoryItemResponseDto } from '../models';
// @ts-ignore
import type { InventoryItemSort } from '../models';
// @ts-ignore
import type { InventoryItemStatus } from '../models';
// @ts-ignore
import type { InventoryItemsControllerSearch200Response } from '../models';
// @ts-ignore
import type { MessageResponseDto } from '../models';
// @ts-ignore
import type { ProductCategory } from '../models';
// @ts-ignore
import type { SurplusUrgency } from '../models';
// @ts-ignore
import type { UpdateInventoryItemDto } from '../models';
/**
 * InventoryItemsApi - axios parameter creator
 * @export
 */
export const InventoryItemsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Log a new inventory item
         * @param {CreateInventoryItemDto} createInventoryItemDto Data to log a new inventory item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerCreate: async (createInventoryItemDto: CreateInventoryItemDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createInventoryItemDto' is not null or undefined
            assertParamExists('inventoryItemsControllerCreate', 'createInventoryItemDto', createInventoryItemDto)
            const localVarPath = `/api/inventory-items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createInventoryItemDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get inventory counts per category and urgency
         * @param {string} [locationId] Branch to count within.
         * @param {InventoryItemStatus} [status] Lifecycle state to count. Defaults to IN_INVENTORY.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerFacets: async (locationId?: string, status?: InventoryItemStatus, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/inventory-items/facets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (locationId !== undefined) {
                localVarQueryParameter['locationId'] = locationId;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get one branch\'s inventory
         * @param {string} locationId Location ID
         * @param {InventoryItemStatus} [status] Narrow the list to one lifecycle state.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerFindAllByLocation: async (locationId: string, status?: InventoryItemStatus, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'locationId' is not null or undefined
            assertParamExists('inventoryItemsControllerFindAllByLocation', 'locationId', locationId)
            const localVarPath = `/api/inventory-items/by-location/{locationId}`
                .replace(`{${"locationId"}}`, encodeURIComponent(String(locationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get one branch\'s near-expiry inventory
         * @param {string} locationId Location ID
         * @param {number} [withinDays] How many days ahead to look. Defaults to 1.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerFindExpiringAtLocation: async (locationId: string, withinDays?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'locationId' is not null or undefined
            assertParamExists('inventoryItemsControllerFindExpiringAtLocation', 'locationId', locationId)
            const localVarPath = `/api/inventory-items/by-location/{locationId}/expiring`
                .replace(`{${"locationId"}}`, encodeURIComponent(String(locationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (withinDays !== undefined) {
                localVarQueryParameter['withinDays'] = withinDays;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get near-expiry or flagged inventory
         * @param {string} [locationId] Branch to look at.
         * @param {number} [withinDays] How many days ahead to look. Defaults to 2.
         * @param {DonationReason} [includeReason] Include lots flagged for this reason whatever their date. ORed with the expiry window, not ANDed.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerFindExpiringOrFlagged: async (locationId?: string, withinDays?: number, includeReason?: DonationReason, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/inventory-items/expiring`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (locationId !== undefined) {
                localVarQueryParameter['locationId'] = locationId;
            }

            if (withinDays !== undefined) {
                localVarQueryParameter['withinDays'] = withinDays;
            }

            if (includeReason !== undefined) {
                localVarQueryParameter['includeReason'] = includeReason;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a single inventory item
         * @param {string} id Inventory item ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('inventoryItemsControllerFindOne', 'id', id)
            const localVarPath = `/api/inventory-items/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete an inventory item by its ID
         * @param {string} id Inventory item ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('inventoryItemsControllerRemove', 'id', id)
            const localVarPath = `/api/inventory-items/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search and page the inventory
         * @param {number} [limit] How many records to return. Defaults to 25.
         * @param {string} [cursor] Opaque cursor from the previous page’s &#x60;meta.nextCursor&#x60;. Omit for the first page.
         * @param {string} [locationId] Narrow to one branch.
         * @param {InventoryItemStatus} [status] Narrow to one lifecycle state.
         * @param {string} [q] Free-text search across product name, brand and barcode. Matches anywhere in the value, not only the start.
         * @param {ProductCategory} [category] Narrow to one product category.
         * @param {DonationReason} [reason] Narrow to one donation reason.
         * @param {SurplusUrgency} [urgency] Narrow to one urgency band, computed from the expiry.
         * @param {boolean} [isListed] Narrow to lots published to the surplus shelf, or withheld.
         * @param {number} [expiringWithinHours] Only lots expiring within this many hours.
         * @param {number} [expiringWithinDays] Only lots expiring within this many days.
         * @param {InventoryItemSort} [sort] How to order the list.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerSearch: async (limit?: number, cursor?: string, locationId?: string, status?: InventoryItemStatus, q?: string, category?: ProductCategory, reason?: DonationReason, urgency?: SurplusUrgency, isListed?: boolean, expiringWithinHours?: number, expiringWithinDays?: number, sort?: InventoryItemSort, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/inventory-items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (locationId !== undefined) {
                localVarQueryParameter['locationId'] = locationId;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (reason !== undefined) {
                localVarQueryParameter['reason'] = reason;
            }

            if (urgency !== undefined) {
                localVarQueryParameter['urgency'] = urgency;
            }

            if (isListed !== undefined) {
                localVarQueryParameter['isListed'] = isListed;
            }

            if (expiringWithinHours !== undefined) {
                localVarQueryParameter['expiringWithinHours'] = expiringWithinHours;
            }

            if (expiringWithinDays !== undefined) {
                localVarQueryParameter['expiringWithinDays'] = expiringWithinDays;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an inventory item
         * @param {string} id ID of the inventory item to update
         * @param {UpdateInventoryItemDto} updateInventoryItemDto New data for the inventory item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerUpdate: async (id: string, updateInventoryItemDto: UpdateInventoryItemDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('inventoryItemsControllerUpdate', 'id', id)
            // verify required parameter 'updateInventoryItemDto' is not null or undefined
            assertParamExists('inventoryItemsControllerUpdate', 'updateInventoryItemDto', updateInventoryItemDto)
            const localVarPath = `/api/inventory-items/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateInventoryItemDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InventoryItemsApi - functional programming interface
 * @export
 */
export const InventoryItemsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InventoryItemsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Log a new inventory item
         * @param {CreateInventoryItemDto} createInventoryItemDto Data to log a new inventory item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inventoryItemsControllerCreate(createInventoryItemDto: CreateInventoryItemDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InventoryItemCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inventoryItemsControllerCreate(createInventoryItemDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryItemsApi.inventoryItemsControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get inventory counts per category and urgency
         * @param {string} [locationId] Branch to count within.
         * @param {InventoryItemStatus} [status] Lifecycle state to count. Defaults to IN_INVENTORY.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inventoryItemsControllerFacets(locationId?: string, status?: InventoryItemStatus, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InventoryFacetsResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inventoryItemsControllerFacets(locationId, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryItemsApi.inventoryItemsControllerFacets']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get one branch\'s inventory
         * @param {string} locationId Location ID
         * @param {InventoryItemStatus} [status] Narrow the list to one lifecycle state.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inventoryItemsControllerFindAllByLocation(locationId: string, status?: InventoryItemStatus, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InventoryItemResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inventoryItemsControllerFindAllByLocation(locationId, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryItemsApi.inventoryItemsControllerFindAllByLocation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get one branch\'s near-expiry inventory
         * @param {string} locationId Location ID
         * @param {number} [withinDays] How many days ahead to look. Defaults to 1.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inventoryItemsControllerFindExpiringAtLocation(locationId: string, withinDays?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InventoryItemResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inventoryItemsControllerFindExpiringAtLocation(locationId, withinDays, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryItemsApi.inventoryItemsControllerFindExpiringAtLocation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get near-expiry or flagged inventory
         * @param {string} [locationId] Branch to look at.
         * @param {number} [withinDays] How many days ahead to look. Defaults to 2.
         * @param {DonationReason} [includeReason] Include lots flagged for this reason whatever their date. ORed with the expiry window, not ANDed.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inventoryItemsControllerFindExpiringOrFlagged(locationId?: string, withinDays?: number, includeReason?: DonationReason, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InventoryItemResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inventoryItemsControllerFindExpiringOrFlagged(locationId, withinDays, includeReason, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryItemsApi.inventoryItemsControllerFindExpiringOrFlagged']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a single inventory item
         * @param {string} id Inventory item ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inventoryItemsControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InventoryItemResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inventoryItemsControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryItemsApi.inventoryItemsControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete an inventory item by its ID
         * @param {string} id Inventory item ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inventoryItemsControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inventoryItemsControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryItemsApi.inventoryItemsControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search and page the inventory
         * @param {number} [limit] How many records to return. Defaults to 25.
         * @param {string} [cursor] Opaque cursor from the previous page’s &#x60;meta.nextCursor&#x60;. Omit for the first page.
         * @param {string} [locationId] Narrow to one branch.
         * @param {InventoryItemStatus} [status] Narrow to one lifecycle state.
         * @param {string} [q] Free-text search across product name, brand and barcode. Matches anywhere in the value, not only the start.
         * @param {ProductCategory} [category] Narrow to one product category.
         * @param {DonationReason} [reason] Narrow to one donation reason.
         * @param {SurplusUrgency} [urgency] Narrow to one urgency band, computed from the expiry.
         * @param {boolean} [isListed] Narrow to lots published to the surplus shelf, or withheld.
         * @param {number} [expiringWithinHours] Only lots expiring within this many hours.
         * @param {number} [expiringWithinDays] Only lots expiring within this many days.
         * @param {InventoryItemSort} [sort] How to order the list.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inventoryItemsControllerSearch(limit?: number, cursor?: string, locationId?: string, status?: InventoryItemStatus, q?: string, category?: ProductCategory, reason?: DonationReason, urgency?: SurplusUrgency, isListed?: boolean, expiringWithinHours?: number, expiringWithinDays?: number, sort?: InventoryItemSort, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InventoryItemsControllerSearch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inventoryItemsControllerSearch(limit, cursor, locationId, status, q, category, reason, urgency, isListed, expiringWithinHours, expiringWithinDays, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryItemsApi.inventoryItemsControllerSearch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an inventory item
         * @param {string} id ID of the inventory item to update
         * @param {UpdateInventoryItemDto} updateInventoryItemDto New data for the inventory item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inventoryItemsControllerUpdate(id: string, updateInventoryItemDto: UpdateInventoryItemDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InventoryItemCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inventoryItemsControllerUpdate(id, updateInventoryItemDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryItemsApi.inventoryItemsControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InventoryItemsApi - factory interface
 * @export
 */
export const InventoryItemsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InventoryItemsApiFp(configuration)
    return {
        /**
         * 
         * @summary Log a new inventory item
         * @param {InventoryItemsApiInventoryItemsControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerCreate(requestParameters: InventoryItemsApiInventoryItemsControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<InventoryItemCreatedResponseDto> {
            return localVarFp.inventoryItemsControllerCreate(requestParameters.createInventoryItemDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get inventory counts per category and urgency
         * @param {InventoryItemsApiInventoryItemsControllerFacetsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerFacets(requestParameters: InventoryItemsApiInventoryItemsControllerFacetsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<InventoryFacetsResponseDto> {
            return localVarFp.inventoryItemsControllerFacets(requestParameters.locationId, requestParameters.status, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get one branch\'s inventory
         * @param {InventoryItemsApiInventoryItemsControllerFindAllByLocationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerFindAllByLocation(requestParameters: InventoryItemsApiInventoryItemsControllerFindAllByLocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<InventoryItemResponseDto>> {
            return localVarFp.inventoryItemsControllerFindAllByLocation(requestParameters.locationId, requestParameters.status, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get one branch\'s near-expiry inventory
         * @param {InventoryItemsApiInventoryItemsControllerFindExpiringAtLocationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerFindExpiringAtLocation(requestParameters: InventoryItemsApiInventoryItemsControllerFindExpiringAtLocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<InventoryItemResponseDto>> {
            return localVarFp.inventoryItemsControllerFindExpiringAtLocation(requestParameters.locationId, requestParameters.withinDays, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get near-expiry or flagged inventory
         * @param {InventoryItemsApiInventoryItemsControllerFindExpiringOrFlaggedRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerFindExpiringOrFlagged(requestParameters: InventoryItemsApiInventoryItemsControllerFindExpiringOrFlaggedRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<InventoryItemResponseDto>> {
            return localVarFp.inventoryItemsControllerFindExpiringOrFlagged(requestParameters.locationId, requestParameters.withinDays, requestParameters.includeReason, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a single inventory item
         * @param {InventoryItemsApiInventoryItemsControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerFindOne(requestParameters: InventoryItemsApiInventoryItemsControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<InventoryItemResponseDto> {
            return localVarFp.inventoryItemsControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete an inventory item by its ID
         * @param {InventoryItemsApiInventoryItemsControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerRemove(requestParameters: InventoryItemsApiInventoryItemsControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto> {
            return localVarFp.inventoryItemsControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search and page the inventory
         * @param {InventoryItemsApiInventoryItemsControllerSearchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerSearch(requestParameters: InventoryItemsApiInventoryItemsControllerSearchRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<InventoryItemsControllerSearch200Response> {
            return localVarFp.inventoryItemsControllerSearch(requestParameters.limit, requestParameters.cursor, requestParameters.locationId, requestParameters.status, requestParameters.q, requestParameters.category, requestParameters.reason, requestParameters.urgency, requestParameters.isListed, requestParameters.expiringWithinHours, requestParameters.expiringWithinDays, requestParameters.sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an inventory item
         * @param {InventoryItemsApiInventoryItemsControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventoryItemsControllerUpdate(requestParameters: InventoryItemsApiInventoryItemsControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<InventoryItemCreatedResponseDto> {
            return localVarFp.inventoryItemsControllerUpdate(requestParameters.id, requestParameters.updateInventoryItemDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InventoryItemsApi - interface
 * @export
 * @interface InventoryItemsApi
 */
export interface InventoryItemsApiInterface {
    /**
     * 
     * @summary Log a new inventory item
     * @param {InventoryItemsApiInventoryItemsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApiInterface
     */
    inventoryItemsControllerCreate(requestParameters: InventoryItemsApiInventoryItemsControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<InventoryItemCreatedResponseDto>;

    /**
     * 
     * @summary Get inventory counts per category and urgency
     * @param {InventoryItemsApiInventoryItemsControllerFacetsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApiInterface
     */
    inventoryItemsControllerFacets(requestParameters?: InventoryItemsApiInventoryItemsControllerFacetsRequest, options?: RawAxiosRequestConfig): AxiosPromise<InventoryFacetsResponseDto>;

    /**
     * 
     * @summary Get one branch\'s inventory
     * @param {InventoryItemsApiInventoryItemsControllerFindAllByLocationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApiInterface
     */
    inventoryItemsControllerFindAllByLocation(requestParameters: InventoryItemsApiInventoryItemsControllerFindAllByLocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<InventoryItemResponseDto>>;

    /**
     * 
     * @summary Get one branch\'s near-expiry inventory
     * @param {InventoryItemsApiInventoryItemsControllerFindExpiringAtLocationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApiInterface
     */
    inventoryItemsControllerFindExpiringAtLocation(requestParameters: InventoryItemsApiInventoryItemsControllerFindExpiringAtLocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<InventoryItemResponseDto>>;

    /**
     * 
     * @summary Get near-expiry or flagged inventory
     * @param {InventoryItemsApiInventoryItemsControllerFindExpiringOrFlaggedRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApiInterface
     */
    inventoryItemsControllerFindExpiringOrFlagged(requestParameters?: InventoryItemsApiInventoryItemsControllerFindExpiringOrFlaggedRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<InventoryItemResponseDto>>;

    /**
     * 
     * @summary Get a single inventory item
     * @param {InventoryItemsApiInventoryItemsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApiInterface
     */
    inventoryItemsControllerFindOne(requestParameters: InventoryItemsApiInventoryItemsControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<InventoryItemResponseDto>;

    /**
     * 
     * @summary Delete an inventory item by its ID
     * @param {InventoryItemsApiInventoryItemsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApiInterface
     */
    inventoryItemsControllerRemove(requestParameters: InventoryItemsApiInventoryItemsControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto>;

    /**
     * 
     * @summary Search and page the inventory
     * @param {InventoryItemsApiInventoryItemsControllerSearchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApiInterface
     */
    inventoryItemsControllerSearch(requestParameters?: InventoryItemsApiInventoryItemsControllerSearchRequest, options?: RawAxiosRequestConfig): AxiosPromise<InventoryItemsControllerSearch200Response>;

    /**
     * 
     * @summary Update an inventory item
     * @param {InventoryItemsApiInventoryItemsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApiInterface
     */
    inventoryItemsControllerUpdate(requestParameters: InventoryItemsApiInventoryItemsControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<InventoryItemCreatedResponseDto>;

}

/**
 * Request parameters for inventoryItemsControllerCreate operation in InventoryItemsApi.
 * @export
 * @interface InventoryItemsApiInventoryItemsControllerCreateRequest
 */
export interface InventoryItemsApiInventoryItemsControllerCreateRequest {
    /**
     * Data to log a new inventory item.
     * @type {CreateInventoryItemDto}
     * @memberof InventoryItemsApiInventoryItemsControllerCreate
     */
    readonly createInventoryItemDto: CreateInventoryItemDto
}

/**
 * Request parameters for inventoryItemsControllerFacets operation in InventoryItemsApi.
 * @export
 * @interface InventoryItemsApiInventoryItemsControllerFacetsRequest
 */
export interface InventoryItemsApiInventoryItemsControllerFacetsRequest {
    /**
     * Branch to count within.
     * @type {string}
     * @memberof InventoryItemsApiInventoryItemsControllerFacets
     */
    readonly locationId?: string

    /**
     * Lifecycle state to count. Defaults to IN_INVENTORY.
     * @type {InventoryItemStatus}
     * @memberof InventoryItemsApiInventoryItemsControllerFacets
     */
    readonly status?: InventoryItemStatus
}

/**
 * Request parameters for inventoryItemsControllerFindAllByLocation operation in InventoryItemsApi.
 * @export
 * @interface InventoryItemsApiInventoryItemsControllerFindAllByLocationRequest
 */
export interface InventoryItemsApiInventoryItemsControllerFindAllByLocationRequest {
    /**
     * Location ID
     * @type {string}
     * @memberof InventoryItemsApiInventoryItemsControllerFindAllByLocation
     */
    readonly locationId: string

    /**
     * Narrow the list to one lifecycle state.
     * @type {InventoryItemStatus}
     * @memberof InventoryItemsApiInventoryItemsControllerFindAllByLocation
     */
    readonly status?: InventoryItemStatus
}

/**
 * Request parameters for inventoryItemsControllerFindExpiringAtLocation operation in InventoryItemsApi.
 * @export
 * @interface InventoryItemsApiInventoryItemsControllerFindExpiringAtLocationRequest
 */
export interface InventoryItemsApiInventoryItemsControllerFindExpiringAtLocationRequest {
    /**
     * Location ID
     * @type {string}
     * @memberof InventoryItemsApiInventoryItemsControllerFindExpiringAtLocation
     */
    readonly locationId: string

    /**
     * How many days ahead to look. Defaults to 1.
     * @type {number}
     * @memberof InventoryItemsApiInventoryItemsControllerFindExpiringAtLocation
     */
    readonly withinDays?: number
}

/**
 * Request parameters for inventoryItemsControllerFindExpiringOrFlagged operation in InventoryItemsApi.
 * @export
 * @interface InventoryItemsApiInventoryItemsControllerFindExpiringOrFlaggedRequest
 */
export interface InventoryItemsApiInventoryItemsControllerFindExpiringOrFlaggedRequest {
    /**
     * Branch to look at.
     * @type {string}
     * @memberof InventoryItemsApiInventoryItemsControllerFindExpiringOrFlagged
     */
    readonly locationId?: string

    /**
     * How many days ahead to look. Defaults to 2.
     * @type {number}
     * @memberof InventoryItemsApiInventoryItemsControllerFindExpiringOrFlagged
     */
    readonly withinDays?: number

    /**
     * Include lots flagged for this reason whatever their date. ORed with the expiry window, not ANDed.
     * @type {DonationReason}
     * @memberof InventoryItemsApiInventoryItemsControllerFindExpiringOrFlagged
     */
    readonly includeReason?: DonationReason
}

/**
 * Request parameters for inventoryItemsControllerFindOne operation in InventoryItemsApi.
 * @export
 * @interface InventoryItemsApiInventoryItemsControllerFindOneRequest
 */
export interface InventoryItemsApiInventoryItemsControllerFindOneRequest {
    /**
     * Inventory item ID
     * @type {string}
     * @memberof InventoryItemsApiInventoryItemsControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for inventoryItemsControllerRemove operation in InventoryItemsApi.
 * @export
 * @interface InventoryItemsApiInventoryItemsControllerRemoveRequest
 */
export interface InventoryItemsApiInventoryItemsControllerRemoveRequest {
    /**
     * Inventory item ID
     * @type {string}
     * @memberof InventoryItemsApiInventoryItemsControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for inventoryItemsControllerSearch operation in InventoryItemsApi.
 * @export
 * @interface InventoryItemsApiInventoryItemsControllerSearchRequest
 */
export interface InventoryItemsApiInventoryItemsControllerSearchRequest {
    /**
     * How many records to return. Defaults to 25.
     * @type {number}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly limit?: number

    /**
     * Opaque cursor from the previous page’s &#x60;meta.nextCursor&#x60;. Omit for the first page.
     * @type {string}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly cursor?: string

    /**
     * Narrow to one branch.
     * @type {string}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly locationId?: string

    /**
     * Narrow to one lifecycle state.
     * @type {InventoryItemStatus}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly status?: InventoryItemStatus

    /**
     * Free-text search across product name, brand and barcode. Matches anywhere in the value, not only the start.
     * @type {string}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly q?: string

    /**
     * Narrow to one product category.
     * @type {ProductCategory}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly category?: ProductCategory

    /**
     * Narrow to one donation reason.
     * @type {DonationReason}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly reason?: DonationReason

    /**
     * Narrow to one urgency band, computed from the expiry.
     * @type {SurplusUrgency}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly urgency?: SurplusUrgency

    /**
     * Narrow to lots published to the surplus shelf, or withheld.
     * @type {boolean}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly isListed?: boolean

    /**
     * Only lots expiring within this many hours.
     * @type {number}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly expiringWithinHours?: number

    /**
     * Only lots expiring within this many days.
     * @type {number}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly expiringWithinDays?: number

    /**
     * How to order the list.
     * @type {InventoryItemSort}
     * @memberof InventoryItemsApiInventoryItemsControllerSearch
     */
    readonly sort?: InventoryItemSort
}

/**
 * Request parameters for inventoryItemsControllerUpdate operation in InventoryItemsApi.
 * @export
 * @interface InventoryItemsApiInventoryItemsControllerUpdateRequest
 */
export interface InventoryItemsApiInventoryItemsControllerUpdateRequest {
    /**
     * ID of the inventory item to update
     * @type {string}
     * @memberof InventoryItemsApiInventoryItemsControllerUpdate
     */
    readonly id: string

    /**
     * New data for the inventory item.
     * @type {UpdateInventoryItemDto}
     * @memberof InventoryItemsApiInventoryItemsControllerUpdate
     */
    readonly updateInventoryItemDto: UpdateInventoryItemDto
}

/**
 * InventoryItemsApi - object-oriented interface
 * @export
 * @class InventoryItemsApi
 * @extends {BaseAPI}
 */
export class InventoryItemsApi extends BaseAPI implements InventoryItemsApiInterface {
    /**
     * 
     * @summary Log a new inventory item
     * @param {InventoryItemsApiInventoryItemsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApi
     */
    public inventoryItemsControllerCreate(requestParameters: InventoryItemsApiInventoryItemsControllerCreateRequest, options?: RawAxiosRequestConfig) {
        return InventoryItemsApiFp(this.configuration).inventoryItemsControllerCreate(requestParameters.createInventoryItemDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get inventory counts per category and urgency
     * @param {InventoryItemsApiInventoryItemsControllerFacetsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApi
     */
    public inventoryItemsControllerFacets(requestParameters: InventoryItemsApiInventoryItemsControllerFacetsRequest = {}, options?: RawAxiosRequestConfig) {
        return InventoryItemsApiFp(this.configuration).inventoryItemsControllerFacets(requestParameters.locationId, requestParameters.status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get one branch\'s inventory
     * @param {InventoryItemsApiInventoryItemsControllerFindAllByLocationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApi
     */
    public inventoryItemsControllerFindAllByLocation(requestParameters: InventoryItemsApiInventoryItemsControllerFindAllByLocationRequest, options?: RawAxiosRequestConfig) {
        return InventoryItemsApiFp(this.configuration).inventoryItemsControllerFindAllByLocation(requestParameters.locationId, requestParameters.status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get one branch\'s near-expiry inventory
     * @param {InventoryItemsApiInventoryItemsControllerFindExpiringAtLocationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApi
     */
    public inventoryItemsControllerFindExpiringAtLocation(requestParameters: InventoryItemsApiInventoryItemsControllerFindExpiringAtLocationRequest, options?: RawAxiosRequestConfig) {
        return InventoryItemsApiFp(this.configuration).inventoryItemsControllerFindExpiringAtLocation(requestParameters.locationId, requestParameters.withinDays, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get near-expiry or flagged inventory
     * @param {InventoryItemsApiInventoryItemsControllerFindExpiringOrFlaggedRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApi
     */
    public inventoryItemsControllerFindExpiringOrFlagged(requestParameters: InventoryItemsApiInventoryItemsControllerFindExpiringOrFlaggedRequest = {}, options?: RawAxiosRequestConfig) {
        return InventoryItemsApiFp(this.configuration).inventoryItemsControllerFindExpiringOrFlagged(requestParameters.locationId, requestParameters.withinDays, requestParameters.includeReason, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a single inventory item
     * @param {InventoryItemsApiInventoryItemsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApi
     */
    public inventoryItemsControllerFindOne(requestParameters: InventoryItemsApiInventoryItemsControllerFindOneRequest, options?: RawAxiosRequestConfig) {
        return InventoryItemsApiFp(this.configuration).inventoryItemsControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete an inventory item by its ID
     * @param {InventoryItemsApiInventoryItemsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApi
     */
    public inventoryItemsControllerRemove(requestParameters: InventoryItemsApiInventoryItemsControllerRemoveRequest, options?: RawAxiosRequestConfig) {
        return InventoryItemsApiFp(this.configuration).inventoryItemsControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search and page the inventory
     * @param {InventoryItemsApiInventoryItemsControllerSearchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApi
     */
    public inventoryItemsControllerSearch(requestParameters: InventoryItemsApiInventoryItemsControllerSearchRequest = {}, options?: RawAxiosRequestConfig) {
        return InventoryItemsApiFp(this.configuration).inventoryItemsControllerSearch(requestParameters.limit, requestParameters.cursor, requestParameters.locationId, requestParameters.status, requestParameters.q, requestParameters.category, requestParameters.reason, requestParameters.urgency, requestParameters.isListed, requestParameters.expiringWithinHours, requestParameters.expiringWithinDays, requestParameters.sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an inventory item
     * @param {InventoryItemsApiInventoryItemsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryItemsApi
     */
    public inventoryItemsControllerUpdate(requestParameters: InventoryItemsApiInventoryItemsControllerUpdateRequest, options?: RawAxiosRequestConfig) {
        return InventoryItemsApiFp(this.configuration).inventoryItemsControllerUpdate(requestParameters.id, requestParameters.updateInventoryItemDto, options).then((request) => request(this.axios, this.basePath));
    }
}

