/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateLocationPickupSlotDto } from '../models';
// @ts-ignore
import type { LocationPickupSlotCreatedResponseDto } from '../models';
// @ts-ignore
import type { LocationPickupSlotResponseDto } from '../models';
// @ts-ignore
import type { MessageResponseDto } from '../models';
// @ts-ignore
import type { UpdateLocationPickupSlotDto } from '../models';
/**
 * LocationPickupSlotsApi - axios parameter creator
 * @export
 */
export const LocationPickupSlotsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Offer a new pickup slot
         * @param {CreateLocationPickupSlotDto} createLocationPickupSlotDto Data to create a new pickup slot.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerCreate: async (createLocationPickupSlotDto: CreateLocationPickupSlotDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createLocationPickupSlotDto' is not null or undefined
            assertParamExists('locationPickupSlotsControllerCreate', 'createLocationPickupSlotDto', createLocationPickupSlotDto)
            const localVarPath = `/api/location-pickup-slots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createLocationPickupSlotDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all pickup slots
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/location-pickup-slots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get one branch\'s active pickup slots
         * @param {string} locationId Location ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerFindAllByLocation: async (locationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'locationId' is not null or undefined
            assertParamExists('locationPickupSlotsControllerFindAllByLocation', 'locationId', locationId)
            const localVarPath = `/api/location-pickup-slots/by-location/{locationId}`
                .replace(`{${"locationId"}}`, encodeURIComponent(String(locationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a single pickup slot
         * @param {string} id LocationPickupSlot ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('locationPickupSlotsControllerFindOne', 'id', id)
            const localVarPath = `/api/location-pickup-slots/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a pickup slot by its ID
         * @param {string} id LocationPickupSlot ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('locationPickupSlotsControllerRemove', 'id', id)
            const localVarPath = `/api/location-pickup-slots/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a pickup slot
         * @param {string} id ID of the pickup slot to update
         * @param {UpdateLocationPickupSlotDto} updateLocationPickupSlotDto New values for the pickup slot.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerUpdate: async (id: string, updateLocationPickupSlotDto: UpdateLocationPickupSlotDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('locationPickupSlotsControllerUpdate', 'id', id)
            // verify required parameter 'updateLocationPickupSlotDto' is not null or undefined
            assertParamExists('locationPickupSlotsControllerUpdate', 'updateLocationPickupSlotDto', updateLocationPickupSlotDto)
            const localVarPath = `/api/location-pickup-slots/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateLocationPickupSlotDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LocationPickupSlotsApi - functional programming interface
 * @export
 */
export const LocationPickupSlotsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LocationPickupSlotsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Offer a new pickup slot
         * @param {CreateLocationPickupSlotDto} createLocationPickupSlotDto Data to create a new pickup slot.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async locationPickupSlotsControllerCreate(createLocationPickupSlotDto: CreateLocationPickupSlotDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LocationPickupSlotCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.locationPickupSlotsControllerCreate(createLocationPickupSlotDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationPickupSlotsApi.locationPickupSlotsControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all pickup slots
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async locationPickupSlotsControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LocationPickupSlotResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.locationPickupSlotsControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationPickupSlotsApi.locationPickupSlotsControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get one branch\'s active pickup slots
         * @param {string} locationId Location ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async locationPickupSlotsControllerFindAllByLocation(locationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LocationPickupSlotResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.locationPickupSlotsControllerFindAllByLocation(locationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationPickupSlotsApi.locationPickupSlotsControllerFindAllByLocation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a single pickup slot
         * @param {string} id LocationPickupSlot ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async locationPickupSlotsControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LocationPickupSlotResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.locationPickupSlotsControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationPickupSlotsApi.locationPickupSlotsControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a pickup slot by its ID
         * @param {string} id LocationPickupSlot ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async locationPickupSlotsControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.locationPickupSlotsControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationPickupSlotsApi.locationPickupSlotsControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a pickup slot
         * @param {string} id ID of the pickup slot to update
         * @param {UpdateLocationPickupSlotDto} updateLocationPickupSlotDto New values for the pickup slot.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async locationPickupSlotsControllerUpdate(id: string, updateLocationPickupSlotDto: UpdateLocationPickupSlotDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LocationPickupSlotCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.locationPickupSlotsControllerUpdate(id, updateLocationPickupSlotDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationPickupSlotsApi.locationPickupSlotsControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LocationPickupSlotsApi - factory interface
 * @export
 */
export const LocationPickupSlotsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LocationPickupSlotsApiFp(configuration)
    return {
        /**
         * 
         * @summary Offer a new pickup slot
         * @param {LocationPickupSlotsApiLocationPickupSlotsControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerCreate(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<LocationPickupSlotCreatedResponseDto> {
            return localVarFp.locationPickupSlotsControllerCreate(requestParameters.createLocationPickupSlotDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all pickup slots
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<LocationPickupSlotResponseDto>> {
            return localVarFp.locationPickupSlotsControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get one branch\'s active pickup slots
         * @param {LocationPickupSlotsApiLocationPickupSlotsControllerFindAllByLocationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerFindAllByLocation(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerFindAllByLocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<LocationPickupSlotResponseDto>> {
            return localVarFp.locationPickupSlotsControllerFindAllByLocation(requestParameters.locationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a single pickup slot
         * @param {LocationPickupSlotsApiLocationPickupSlotsControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerFindOne(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<LocationPickupSlotResponseDto> {
            return localVarFp.locationPickupSlotsControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a pickup slot by its ID
         * @param {LocationPickupSlotsApiLocationPickupSlotsControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerRemove(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto> {
            return localVarFp.locationPickupSlotsControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a pickup slot
         * @param {LocationPickupSlotsApiLocationPickupSlotsControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationPickupSlotsControllerUpdate(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<LocationPickupSlotCreatedResponseDto> {
            return localVarFp.locationPickupSlotsControllerUpdate(requestParameters.id, requestParameters.updateLocationPickupSlotDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LocationPickupSlotsApi - interface
 * @export
 * @interface LocationPickupSlotsApi
 */
export interface LocationPickupSlotsApiInterface {
    /**
     * 
     * @summary Offer a new pickup slot
     * @param {LocationPickupSlotsApiLocationPickupSlotsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApiInterface
     */
    locationPickupSlotsControllerCreate(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<LocationPickupSlotCreatedResponseDto>;

    /**
     * 
     * @summary Get all pickup slots
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApiInterface
     */
    locationPickupSlotsControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<LocationPickupSlotResponseDto>>;

    /**
     * 
     * @summary Get one branch\'s active pickup slots
     * @param {LocationPickupSlotsApiLocationPickupSlotsControllerFindAllByLocationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApiInterface
     */
    locationPickupSlotsControllerFindAllByLocation(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerFindAllByLocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<LocationPickupSlotResponseDto>>;

    /**
     * 
     * @summary Get a single pickup slot
     * @param {LocationPickupSlotsApiLocationPickupSlotsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApiInterface
     */
    locationPickupSlotsControllerFindOne(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<LocationPickupSlotResponseDto>;

    /**
     * 
     * @summary Delete a pickup slot by its ID
     * @param {LocationPickupSlotsApiLocationPickupSlotsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApiInterface
     */
    locationPickupSlotsControllerRemove(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto>;

    /**
     * 
     * @summary Update a pickup slot
     * @param {LocationPickupSlotsApiLocationPickupSlotsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApiInterface
     */
    locationPickupSlotsControllerUpdate(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<LocationPickupSlotCreatedResponseDto>;

}

/**
 * Request parameters for locationPickupSlotsControllerCreate operation in LocationPickupSlotsApi.
 * @export
 * @interface LocationPickupSlotsApiLocationPickupSlotsControllerCreateRequest
 */
export interface LocationPickupSlotsApiLocationPickupSlotsControllerCreateRequest {
    /**
     * Data to create a new pickup slot.
     * @type {CreateLocationPickupSlotDto}
     * @memberof LocationPickupSlotsApiLocationPickupSlotsControllerCreate
     */
    readonly createLocationPickupSlotDto: CreateLocationPickupSlotDto
}

/**
 * Request parameters for locationPickupSlotsControllerFindAllByLocation operation in LocationPickupSlotsApi.
 * @export
 * @interface LocationPickupSlotsApiLocationPickupSlotsControllerFindAllByLocationRequest
 */
export interface LocationPickupSlotsApiLocationPickupSlotsControllerFindAllByLocationRequest {
    /**
     * Location ID
     * @type {string}
     * @memberof LocationPickupSlotsApiLocationPickupSlotsControllerFindAllByLocation
     */
    readonly locationId: string
}

/**
 * Request parameters for locationPickupSlotsControllerFindOne operation in LocationPickupSlotsApi.
 * @export
 * @interface LocationPickupSlotsApiLocationPickupSlotsControllerFindOneRequest
 */
export interface LocationPickupSlotsApiLocationPickupSlotsControllerFindOneRequest {
    /**
     * LocationPickupSlot ID
     * @type {string}
     * @memberof LocationPickupSlotsApiLocationPickupSlotsControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for locationPickupSlotsControllerRemove operation in LocationPickupSlotsApi.
 * @export
 * @interface LocationPickupSlotsApiLocationPickupSlotsControllerRemoveRequest
 */
export interface LocationPickupSlotsApiLocationPickupSlotsControllerRemoveRequest {
    /**
     * LocationPickupSlot ID
     * @type {string}
     * @memberof LocationPickupSlotsApiLocationPickupSlotsControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for locationPickupSlotsControllerUpdate operation in LocationPickupSlotsApi.
 * @export
 * @interface LocationPickupSlotsApiLocationPickupSlotsControllerUpdateRequest
 */
export interface LocationPickupSlotsApiLocationPickupSlotsControllerUpdateRequest {
    /**
     * ID of the pickup slot to update
     * @type {string}
     * @memberof LocationPickupSlotsApiLocationPickupSlotsControllerUpdate
     */
    readonly id: string

    /**
     * New values for the pickup slot.
     * @type {UpdateLocationPickupSlotDto}
     * @memberof LocationPickupSlotsApiLocationPickupSlotsControllerUpdate
     */
    readonly updateLocationPickupSlotDto: UpdateLocationPickupSlotDto
}

/**
 * LocationPickupSlotsApi - object-oriented interface
 * @export
 * @class LocationPickupSlotsApi
 * @extends {BaseAPI}
 */
export class LocationPickupSlotsApi extends BaseAPI implements LocationPickupSlotsApiInterface {
    /**
     * 
     * @summary Offer a new pickup slot
     * @param {LocationPickupSlotsApiLocationPickupSlotsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApi
     */
    public locationPickupSlotsControllerCreate(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerCreateRequest, options?: RawAxiosRequestConfig) {
        return LocationPickupSlotsApiFp(this.configuration).locationPickupSlotsControllerCreate(requestParameters.createLocationPickupSlotDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all pickup slots
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApi
     */
    public locationPickupSlotsControllerFindAll(options?: RawAxiosRequestConfig) {
        return LocationPickupSlotsApiFp(this.configuration).locationPickupSlotsControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get one branch\'s active pickup slots
     * @param {LocationPickupSlotsApiLocationPickupSlotsControllerFindAllByLocationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApi
     */
    public locationPickupSlotsControllerFindAllByLocation(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerFindAllByLocationRequest, options?: RawAxiosRequestConfig) {
        return LocationPickupSlotsApiFp(this.configuration).locationPickupSlotsControllerFindAllByLocation(requestParameters.locationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a single pickup slot
     * @param {LocationPickupSlotsApiLocationPickupSlotsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApi
     */
    public locationPickupSlotsControllerFindOne(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerFindOneRequest, options?: RawAxiosRequestConfig) {
        return LocationPickupSlotsApiFp(this.configuration).locationPickupSlotsControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a pickup slot by its ID
     * @param {LocationPickupSlotsApiLocationPickupSlotsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApi
     */
    public locationPickupSlotsControllerRemove(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerRemoveRequest, options?: RawAxiosRequestConfig) {
        return LocationPickupSlotsApiFp(this.configuration).locationPickupSlotsControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a pickup slot
     * @param {LocationPickupSlotsApiLocationPickupSlotsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationPickupSlotsApi
     */
    public locationPickupSlotsControllerUpdate(requestParameters: LocationPickupSlotsApiLocationPickupSlotsControllerUpdateRequest, options?: RawAxiosRequestConfig) {
        return LocationPickupSlotsApiFp(this.configuration).locationPickupSlotsControllerUpdate(requestParameters.id, requestParameters.updateLocationPickupSlotDto, options).then((request) => request(this.axios, this.basePath));
    }
}

