/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreatePartnershipDto } from '../models';
// @ts-ignore
import type { MessageResponseDto } from '../models';
// @ts-ignore
import type { PartnershipCreatedResponseDto } from '../models';
// @ts-ignore
import type { PartnershipResponseDto } from '../models';
// @ts-ignore
import type { UpdatePartnershipDto } from '../models';
/**
 * PartnershipsApi - axios parameter creator
 * @export
 */
export const PartnershipsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new partnership
         * @param {CreatePartnershipDto} createPartnershipDto Data to create a new partnership.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerCreate: async (createPartnershipDto: CreatePartnershipDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createPartnershipDto' is not null or undefined
            assertParamExists('partnershipsControllerCreate', 'createPartnershipDto', createPartnershipDto)
            const localVarPath = `/api/partnerships`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPartnershipDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all partnerships
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/partnerships`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get one retailer\'s partnerships
         * @param {string} retailerId Retailer ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerFindAllByRetailer: async (retailerId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'retailerId' is not null or undefined
            assertParamExists('partnershipsControllerFindAllByRetailer', 'retailerId', retailerId)
            const localVarPath = `/api/partnerships/by-retailer/{retailerId}`
                .replace(`{${"retailerId"}}`, encodeURIComponent(String(retailerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a single partnership
         * @param {string} id Partnership ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('partnershipsControllerFindOne', 'id', id)
            const localVarPath = `/api/partnerships/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a partnership by its ID
         * @param {string} id Partnership ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('partnershipsControllerRemove', 'id', id)
            const localVarPath = `/api/partnerships/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a partnership
         * @param {string} id ID of the partnership to update
         * @param {UpdatePartnershipDto} updatePartnershipDto New data for the partnership.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerUpdate: async (id: string, updatePartnershipDto: UpdatePartnershipDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('partnershipsControllerUpdate', 'id', id)
            // verify required parameter 'updatePartnershipDto' is not null or undefined
            assertParamExists('partnershipsControllerUpdate', 'updatePartnershipDto', updatePartnershipDto)
            const localVarPath = `/api/partnerships/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePartnershipDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PartnershipsApi - functional programming interface
 * @export
 */
export const PartnershipsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PartnershipsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new partnership
         * @param {CreatePartnershipDto} createPartnershipDto Data to create a new partnership.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async partnershipsControllerCreate(createPartnershipDto: CreatePartnershipDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PartnershipCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.partnershipsControllerCreate(createPartnershipDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PartnershipsApi.partnershipsControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all partnerships
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async partnershipsControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PartnershipResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.partnershipsControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PartnershipsApi.partnershipsControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get one retailer\'s partnerships
         * @param {string} retailerId Retailer ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async partnershipsControllerFindAllByRetailer(retailerId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PartnershipResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.partnershipsControllerFindAllByRetailer(retailerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PartnershipsApi.partnershipsControllerFindAllByRetailer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a single partnership
         * @param {string} id Partnership ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async partnershipsControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PartnershipResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.partnershipsControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PartnershipsApi.partnershipsControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a partnership by its ID
         * @param {string} id Partnership ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async partnershipsControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.partnershipsControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PartnershipsApi.partnershipsControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a partnership
         * @param {string} id ID of the partnership to update
         * @param {UpdatePartnershipDto} updatePartnershipDto New data for the partnership.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async partnershipsControllerUpdate(id: string, updatePartnershipDto: UpdatePartnershipDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PartnershipCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.partnershipsControllerUpdate(id, updatePartnershipDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PartnershipsApi.partnershipsControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PartnershipsApi - factory interface
 * @export
 */
export const PartnershipsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PartnershipsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new partnership
         * @param {PartnershipsApiPartnershipsControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerCreate(requestParameters: PartnershipsApiPartnershipsControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<PartnershipCreatedResponseDto> {
            return localVarFp.partnershipsControllerCreate(requestParameters.createPartnershipDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all partnerships
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<PartnershipResponseDto>> {
            return localVarFp.partnershipsControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get one retailer\'s partnerships
         * @param {PartnershipsApiPartnershipsControllerFindAllByRetailerRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerFindAllByRetailer(requestParameters: PartnershipsApiPartnershipsControllerFindAllByRetailerRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<PartnershipResponseDto>> {
            return localVarFp.partnershipsControllerFindAllByRetailer(requestParameters.retailerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a single partnership
         * @param {PartnershipsApiPartnershipsControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerFindOne(requestParameters: PartnershipsApiPartnershipsControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<PartnershipResponseDto> {
            return localVarFp.partnershipsControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a partnership by its ID
         * @param {PartnershipsApiPartnershipsControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerRemove(requestParameters: PartnershipsApiPartnershipsControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto> {
            return localVarFp.partnershipsControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a partnership
         * @param {PartnershipsApiPartnershipsControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partnershipsControllerUpdate(requestParameters: PartnershipsApiPartnershipsControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<PartnershipCreatedResponseDto> {
            return localVarFp.partnershipsControllerUpdate(requestParameters.id, requestParameters.updatePartnershipDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PartnershipsApi - interface
 * @export
 * @interface PartnershipsApi
 */
export interface PartnershipsApiInterface {
    /**
     * 
     * @summary Create a new partnership
     * @param {PartnershipsApiPartnershipsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApiInterface
     */
    partnershipsControllerCreate(requestParameters: PartnershipsApiPartnershipsControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<PartnershipCreatedResponseDto>;

    /**
     * 
     * @summary Get all partnerships
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApiInterface
     */
    partnershipsControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<PartnershipResponseDto>>;

    /**
     * 
     * @summary Get one retailer\'s partnerships
     * @param {PartnershipsApiPartnershipsControllerFindAllByRetailerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApiInterface
     */
    partnershipsControllerFindAllByRetailer(requestParameters: PartnershipsApiPartnershipsControllerFindAllByRetailerRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<PartnershipResponseDto>>;

    /**
     * 
     * @summary Get a single partnership
     * @param {PartnershipsApiPartnershipsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApiInterface
     */
    partnershipsControllerFindOne(requestParameters: PartnershipsApiPartnershipsControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<PartnershipResponseDto>;

    /**
     * 
     * @summary Delete a partnership by its ID
     * @param {PartnershipsApiPartnershipsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApiInterface
     */
    partnershipsControllerRemove(requestParameters: PartnershipsApiPartnershipsControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto>;

    /**
     * 
     * @summary Update a partnership
     * @param {PartnershipsApiPartnershipsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApiInterface
     */
    partnershipsControllerUpdate(requestParameters: PartnershipsApiPartnershipsControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<PartnershipCreatedResponseDto>;

}

/**
 * Request parameters for partnershipsControllerCreate operation in PartnershipsApi.
 * @export
 * @interface PartnershipsApiPartnershipsControllerCreateRequest
 */
export interface PartnershipsApiPartnershipsControllerCreateRequest {
    /**
     * Data to create a new partnership.
     * @type {CreatePartnershipDto}
     * @memberof PartnershipsApiPartnershipsControllerCreate
     */
    readonly createPartnershipDto: CreatePartnershipDto
}

/**
 * Request parameters for partnershipsControllerFindAllByRetailer operation in PartnershipsApi.
 * @export
 * @interface PartnershipsApiPartnershipsControllerFindAllByRetailerRequest
 */
export interface PartnershipsApiPartnershipsControllerFindAllByRetailerRequest {
    /**
     * Retailer ID
     * @type {string}
     * @memberof PartnershipsApiPartnershipsControllerFindAllByRetailer
     */
    readonly retailerId: string
}

/**
 * Request parameters for partnershipsControllerFindOne operation in PartnershipsApi.
 * @export
 * @interface PartnershipsApiPartnershipsControllerFindOneRequest
 */
export interface PartnershipsApiPartnershipsControllerFindOneRequest {
    /**
     * Partnership ID
     * @type {string}
     * @memberof PartnershipsApiPartnershipsControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for partnershipsControllerRemove operation in PartnershipsApi.
 * @export
 * @interface PartnershipsApiPartnershipsControllerRemoveRequest
 */
export interface PartnershipsApiPartnershipsControllerRemoveRequest {
    /**
     * Partnership ID
     * @type {string}
     * @memberof PartnershipsApiPartnershipsControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for partnershipsControllerUpdate operation in PartnershipsApi.
 * @export
 * @interface PartnershipsApiPartnershipsControllerUpdateRequest
 */
export interface PartnershipsApiPartnershipsControllerUpdateRequest {
    /**
     * ID of the partnership to update
     * @type {string}
     * @memberof PartnershipsApiPartnershipsControllerUpdate
     */
    readonly id: string

    /**
     * New data for the partnership.
     * @type {UpdatePartnershipDto}
     * @memberof PartnershipsApiPartnershipsControllerUpdate
     */
    readonly updatePartnershipDto: UpdatePartnershipDto
}

/**
 * PartnershipsApi - object-oriented interface
 * @export
 * @class PartnershipsApi
 * @extends {BaseAPI}
 */
export class PartnershipsApi extends BaseAPI implements PartnershipsApiInterface {
    /**
     * 
     * @summary Create a new partnership
     * @param {PartnershipsApiPartnershipsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApi
     */
    public partnershipsControllerCreate(requestParameters: PartnershipsApiPartnershipsControllerCreateRequest, options?: RawAxiosRequestConfig) {
        return PartnershipsApiFp(this.configuration).partnershipsControllerCreate(requestParameters.createPartnershipDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all partnerships
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApi
     */
    public partnershipsControllerFindAll(options?: RawAxiosRequestConfig) {
        return PartnershipsApiFp(this.configuration).partnershipsControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get one retailer\'s partnerships
     * @param {PartnershipsApiPartnershipsControllerFindAllByRetailerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApi
     */
    public partnershipsControllerFindAllByRetailer(requestParameters: PartnershipsApiPartnershipsControllerFindAllByRetailerRequest, options?: RawAxiosRequestConfig) {
        return PartnershipsApiFp(this.configuration).partnershipsControllerFindAllByRetailer(requestParameters.retailerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a single partnership
     * @param {PartnershipsApiPartnershipsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApi
     */
    public partnershipsControllerFindOne(requestParameters: PartnershipsApiPartnershipsControllerFindOneRequest, options?: RawAxiosRequestConfig) {
        return PartnershipsApiFp(this.configuration).partnershipsControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a partnership by its ID
     * @param {PartnershipsApiPartnershipsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApi
     */
    public partnershipsControllerRemove(requestParameters: PartnershipsApiPartnershipsControllerRemoveRequest, options?: RawAxiosRequestConfig) {
        return PartnershipsApiFp(this.configuration).partnershipsControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a partnership
     * @param {PartnershipsApiPartnershipsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnershipsApi
     */
    public partnershipsControllerUpdate(requestParameters: PartnershipsApiPartnershipsControllerUpdateRequest, options?: RawAxiosRequestConfig) {
        return PartnershipsApiFp(this.configuration).partnershipsControllerUpdate(requestParameters.id, requestParameters.updatePartnershipDto, options).then((request) => request(this.axios, this.basePath));
    }
}

