/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateRecipientVehicleDto } from '../models';
// @ts-ignore
import type { MessageResponseDto } from '../models';
// @ts-ignore
import type { RecipientVehicleCreatedResponseDto } from '../models';
// @ts-ignore
import type { RecipientVehicleResponseDto } from '../models';
// @ts-ignore
import type { UpdateRecipientVehicleDto } from '../models';
/**
 * RecipientVehiclesApi - axios parameter creator
 * @export
 */
export const RecipientVehiclesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new vehicle
         * @param {CreateRecipientVehicleDto} createRecipientVehicleDto Data to create a new vehicle.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerCreate: async (createRecipientVehicleDto: CreateRecipientVehicleDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createRecipientVehicleDto' is not null or undefined
            assertParamExists('recipientVehiclesControllerCreate', 'createRecipientVehicleDto', createRecipientVehicleDto)
            const localVarPath = `/api/recipient-vehicles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createRecipientVehicleDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all vehicles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/recipient-vehicles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get one recipient\'s vehicles
         * @param {string} recipientId Recipient ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerFindAllByRecipient: async (recipientId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recipientId' is not null or undefined
            assertParamExists('recipientVehiclesControllerFindAllByRecipient', 'recipientId', recipientId)
            const localVarPath = `/api/recipient-vehicles/by-recipient/{recipientId}`
                .replace(`{${"recipientId"}}`, encodeURIComponent(String(recipientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a single vehicle
         * @param {string} id RecipientVehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recipientVehiclesControllerFindOne', 'id', id)
            const localVarPath = `/api/recipient-vehicles/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a vehicle by its ID
         * @param {string} id RecipientVehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recipientVehiclesControllerRemove', 'id', id)
            const localVarPath = `/api/recipient-vehicles/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a vehicle
         * @param {string} id ID of the vehicle to update
         * @param {UpdateRecipientVehicleDto} updateRecipientVehicleDto New data for the vehicle.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerUpdate: async (id: string, updateRecipientVehicleDto: UpdateRecipientVehicleDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recipientVehiclesControllerUpdate', 'id', id)
            // verify required parameter 'updateRecipientVehicleDto' is not null or undefined
            assertParamExists('recipientVehiclesControllerUpdate', 'updateRecipientVehicleDto', updateRecipientVehicleDto)
            const localVarPath = `/api/recipient-vehicles/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateRecipientVehicleDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecipientVehiclesApi - functional programming interface
 * @export
 */
export const RecipientVehiclesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecipientVehiclesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new vehicle
         * @param {CreateRecipientVehicleDto} createRecipientVehicleDto Data to create a new vehicle.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipientVehiclesControllerCreate(createRecipientVehicleDto: CreateRecipientVehicleDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecipientVehicleCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipientVehiclesControllerCreate(createRecipientVehicleDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipientVehiclesApi.recipientVehiclesControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all vehicles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipientVehiclesControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RecipientVehicleResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipientVehiclesControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipientVehiclesApi.recipientVehiclesControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get one recipient\'s vehicles
         * @param {string} recipientId Recipient ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipientVehiclesControllerFindAllByRecipient(recipientId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RecipientVehicleResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipientVehiclesControllerFindAllByRecipient(recipientId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipientVehiclesApi.recipientVehiclesControllerFindAllByRecipient']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a single vehicle
         * @param {string} id RecipientVehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipientVehiclesControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecipientVehicleResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipientVehiclesControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipientVehiclesApi.recipientVehiclesControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a vehicle by its ID
         * @param {string} id RecipientVehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipientVehiclesControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipientVehiclesControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipientVehiclesApi.recipientVehiclesControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a vehicle
         * @param {string} id ID of the vehicle to update
         * @param {UpdateRecipientVehicleDto} updateRecipientVehicleDto New data for the vehicle.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipientVehiclesControllerUpdate(id: string, updateRecipientVehicleDto: UpdateRecipientVehicleDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecipientVehicleCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipientVehiclesControllerUpdate(id, updateRecipientVehicleDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipientVehiclesApi.recipientVehiclesControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RecipientVehiclesApi - factory interface
 * @export
 */
export const RecipientVehiclesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecipientVehiclesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new vehicle
         * @param {RecipientVehiclesApiRecipientVehiclesControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerCreate(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientVehicleCreatedResponseDto> {
            return localVarFp.recipientVehiclesControllerCreate(requestParameters.createRecipientVehicleDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all vehicles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<RecipientVehicleResponseDto>> {
            return localVarFp.recipientVehiclesControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get one recipient\'s vehicles
         * @param {RecipientVehiclesApiRecipientVehiclesControllerFindAllByRecipientRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerFindAllByRecipient(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerFindAllByRecipientRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<RecipientVehicleResponseDto>> {
            return localVarFp.recipientVehiclesControllerFindAllByRecipient(requestParameters.recipientId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a single vehicle
         * @param {RecipientVehiclesApiRecipientVehiclesControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerFindOne(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientVehicleResponseDto> {
            return localVarFp.recipientVehiclesControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a vehicle by its ID
         * @param {RecipientVehiclesApiRecipientVehiclesControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerRemove(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto> {
            return localVarFp.recipientVehiclesControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a vehicle
         * @param {RecipientVehiclesApiRecipientVehiclesControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientVehiclesControllerUpdate(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientVehicleCreatedResponseDto> {
            return localVarFp.recipientVehiclesControllerUpdate(requestParameters.id, requestParameters.updateRecipientVehicleDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecipientVehiclesApi - interface
 * @export
 * @interface RecipientVehiclesApi
 */
export interface RecipientVehiclesApiInterface {
    /**
     * 
     * @summary Create a new vehicle
     * @param {RecipientVehiclesApiRecipientVehiclesControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApiInterface
     */
    recipientVehiclesControllerCreate(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientVehicleCreatedResponseDto>;

    /**
     * 
     * @summary Get all vehicles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApiInterface
     */
    recipientVehiclesControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<RecipientVehicleResponseDto>>;

    /**
     * 
     * @summary Get one recipient\'s vehicles
     * @param {RecipientVehiclesApiRecipientVehiclesControllerFindAllByRecipientRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApiInterface
     */
    recipientVehiclesControllerFindAllByRecipient(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerFindAllByRecipientRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<RecipientVehicleResponseDto>>;

    /**
     * 
     * @summary Get a single vehicle
     * @param {RecipientVehiclesApiRecipientVehiclesControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApiInterface
     */
    recipientVehiclesControllerFindOne(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientVehicleResponseDto>;

    /**
     * 
     * @summary Delete a vehicle by its ID
     * @param {RecipientVehiclesApiRecipientVehiclesControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApiInterface
     */
    recipientVehiclesControllerRemove(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto>;

    /**
     * 
     * @summary Update a vehicle
     * @param {RecipientVehiclesApiRecipientVehiclesControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApiInterface
     */
    recipientVehiclesControllerUpdate(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientVehicleCreatedResponseDto>;

}

/**
 * Request parameters for recipientVehiclesControllerCreate operation in RecipientVehiclesApi.
 * @export
 * @interface RecipientVehiclesApiRecipientVehiclesControllerCreateRequest
 */
export interface RecipientVehiclesApiRecipientVehiclesControllerCreateRequest {
    /**
     * Data to create a new vehicle.
     * @type {CreateRecipientVehicleDto}
     * @memberof RecipientVehiclesApiRecipientVehiclesControllerCreate
     */
    readonly createRecipientVehicleDto: CreateRecipientVehicleDto
}

/**
 * Request parameters for recipientVehiclesControllerFindAllByRecipient operation in RecipientVehiclesApi.
 * @export
 * @interface RecipientVehiclesApiRecipientVehiclesControllerFindAllByRecipientRequest
 */
export interface RecipientVehiclesApiRecipientVehiclesControllerFindAllByRecipientRequest {
    /**
     * Recipient ID
     * @type {string}
     * @memberof RecipientVehiclesApiRecipientVehiclesControllerFindAllByRecipient
     */
    readonly recipientId: string
}

/**
 * Request parameters for recipientVehiclesControllerFindOne operation in RecipientVehiclesApi.
 * @export
 * @interface RecipientVehiclesApiRecipientVehiclesControllerFindOneRequest
 */
export interface RecipientVehiclesApiRecipientVehiclesControllerFindOneRequest {
    /**
     * RecipientVehicle ID
     * @type {string}
     * @memberof RecipientVehiclesApiRecipientVehiclesControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for recipientVehiclesControllerRemove operation in RecipientVehiclesApi.
 * @export
 * @interface RecipientVehiclesApiRecipientVehiclesControllerRemoveRequest
 */
export interface RecipientVehiclesApiRecipientVehiclesControllerRemoveRequest {
    /**
     * RecipientVehicle ID
     * @type {string}
     * @memberof RecipientVehiclesApiRecipientVehiclesControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for recipientVehiclesControllerUpdate operation in RecipientVehiclesApi.
 * @export
 * @interface RecipientVehiclesApiRecipientVehiclesControllerUpdateRequest
 */
export interface RecipientVehiclesApiRecipientVehiclesControllerUpdateRequest {
    /**
     * ID of the vehicle to update
     * @type {string}
     * @memberof RecipientVehiclesApiRecipientVehiclesControllerUpdate
     */
    readonly id: string

    /**
     * New data for the vehicle.
     * @type {UpdateRecipientVehicleDto}
     * @memberof RecipientVehiclesApiRecipientVehiclesControllerUpdate
     */
    readonly updateRecipientVehicleDto: UpdateRecipientVehicleDto
}

/**
 * RecipientVehiclesApi - object-oriented interface
 * @export
 * @class RecipientVehiclesApi
 * @extends {BaseAPI}
 */
export class RecipientVehiclesApi extends BaseAPI implements RecipientVehiclesApiInterface {
    /**
     * 
     * @summary Create a new vehicle
     * @param {RecipientVehiclesApiRecipientVehiclesControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApi
     */
    public recipientVehiclesControllerCreate(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerCreateRequest, options?: RawAxiosRequestConfig) {
        return RecipientVehiclesApiFp(this.configuration).recipientVehiclesControllerCreate(requestParameters.createRecipientVehicleDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all vehicles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApi
     */
    public recipientVehiclesControllerFindAll(options?: RawAxiosRequestConfig) {
        return RecipientVehiclesApiFp(this.configuration).recipientVehiclesControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get one recipient\'s vehicles
     * @param {RecipientVehiclesApiRecipientVehiclesControllerFindAllByRecipientRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApi
     */
    public recipientVehiclesControllerFindAllByRecipient(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerFindAllByRecipientRequest, options?: RawAxiosRequestConfig) {
        return RecipientVehiclesApiFp(this.configuration).recipientVehiclesControllerFindAllByRecipient(requestParameters.recipientId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a single vehicle
     * @param {RecipientVehiclesApiRecipientVehiclesControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApi
     */
    public recipientVehiclesControllerFindOne(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerFindOneRequest, options?: RawAxiosRequestConfig) {
        return RecipientVehiclesApiFp(this.configuration).recipientVehiclesControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a vehicle by its ID
     * @param {RecipientVehiclesApiRecipientVehiclesControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApi
     */
    public recipientVehiclesControllerRemove(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerRemoveRequest, options?: RawAxiosRequestConfig) {
        return RecipientVehiclesApiFp(this.configuration).recipientVehiclesControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a vehicle
     * @param {RecipientVehiclesApiRecipientVehiclesControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientVehiclesApi
     */
    public recipientVehiclesControllerUpdate(requestParameters: RecipientVehiclesApiRecipientVehiclesControllerUpdateRequest, options?: RawAxiosRequestConfig) {
        return RecipientVehiclesApiFp(this.configuration).recipientVehiclesControllerUpdate(requestParameters.id, requestParameters.updateRecipientVehicleDto, options).then((request) => request(this.axios, this.basePath));
    }
}

