/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateRecipientDto } from '../models';
// @ts-ignore
import type { MessageResponseDto } from '../models';
// @ts-ignore
import type { RecipientCreatedResponseDto } from '../models';
// @ts-ignore
import type { RecipientResponseDto } from '../models';
// @ts-ignore
import type { UpdateRecipientDto } from '../models';
/**
 * RecipientsApi - axios parameter creator
 * @export
 */
export const RecipientsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new recipient
         * @param {CreateRecipientDto} createRecipientDto Data to create a new recipient.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientsControllerCreate: async (createRecipientDto: CreateRecipientDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createRecipientDto' is not null or undefined
            assertParamExists('recipientsControllerCreate', 'createRecipientDto', createRecipientDto)
            const localVarPath = `/api/recipients`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createRecipientDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all recipients
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientsControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/recipients`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a single recipient
         * @param {string} id Recipient ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientsControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recipientsControllerFindOne', 'id', id)
            const localVarPath = `/api/recipients/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a recipient by its ID
         * @param {string} id Recipient ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientsControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recipientsControllerRemove', 'id', id)
            const localVarPath = `/api/recipients/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a recipient
         * @param {string} id ID of the recipient to update
         * @param {UpdateRecipientDto} updateRecipientDto New data for the recipient.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientsControllerUpdate: async (id: string, updateRecipientDto: UpdateRecipientDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recipientsControllerUpdate', 'id', id)
            // verify required parameter 'updateRecipientDto' is not null or undefined
            assertParamExists('recipientsControllerUpdate', 'updateRecipientDto', updateRecipientDto)
            const localVarPath = `/api/recipients/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateRecipientDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecipientsApi - functional programming interface
 * @export
 */
export const RecipientsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecipientsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new recipient
         * @param {CreateRecipientDto} createRecipientDto Data to create a new recipient.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipientsControllerCreate(createRecipientDto: CreateRecipientDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecipientCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipientsControllerCreate(createRecipientDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipientsApi.recipientsControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all recipients
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipientsControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RecipientResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipientsControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipientsApi.recipientsControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a single recipient
         * @param {string} id Recipient ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipientsControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecipientResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipientsControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipientsApi.recipientsControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a recipient by its ID
         * @param {string} id Recipient ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipientsControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipientsControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipientsApi.recipientsControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a recipient
         * @param {string} id ID of the recipient to update
         * @param {UpdateRecipientDto} updateRecipientDto New data for the recipient.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipientsControllerUpdate(id: string, updateRecipientDto: UpdateRecipientDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecipientCreatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipientsControllerUpdate(id, updateRecipientDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipientsApi.recipientsControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RecipientsApi - factory interface
 * @export
 */
export const RecipientsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecipientsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new recipient
         * @param {RecipientsApiRecipientsControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientsControllerCreate(requestParameters: RecipientsApiRecipientsControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientCreatedResponseDto> {
            return localVarFp.recipientsControllerCreate(requestParameters.createRecipientDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all recipients
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientsControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<RecipientResponseDto>> {
            return localVarFp.recipientsControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a single recipient
         * @param {RecipientsApiRecipientsControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientsControllerFindOne(requestParameters: RecipientsApiRecipientsControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientResponseDto> {
            return localVarFp.recipientsControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a recipient by its ID
         * @param {RecipientsApiRecipientsControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientsControllerRemove(requestParameters: RecipientsApiRecipientsControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto> {
            return localVarFp.recipientsControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a recipient
         * @param {RecipientsApiRecipientsControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipientsControllerUpdate(requestParameters: RecipientsApiRecipientsControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientCreatedResponseDto> {
            return localVarFp.recipientsControllerUpdate(requestParameters.id, requestParameters.updateRecipientDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecipientsApi - interface
 * @export
 * @interface RecipientsApi
 */
export interface RecipientsApiInterface {
    /**
     * 
     * @summary Create a new recipient
     * @param {RecipientsApiRecipientsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientsApiInterface
     */
    recipientsControllerCreate(requestParameters: RecipientsApiRecipientsControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientCreatedResponseDto>;

    /**
     * 
     * @summary Get all recipients
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientsApiInterface
     */
    recipientsControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<RecipientResponseDto>>;

    /**
     * 
     * @summary Get a single recipient
     * @param {RecipientsApiRecipientsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientsApiInterface
     */
    recipientsControllerFindOne(requestParameters: RecipientsApiRecipientsControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientResponseDto>;

    /**
     * 
     * @summary Delete a recipient by its ID
     * @param {RecipientsApiRecipientsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientsApiInterface
     */
    recipientsControllerRemove(requestParameters: RecipientsApiRecipientsControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponseDto>;

    /**
     * 
     * @summary Update a recipient
     * @param {RecipientsApiRecipientsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientsApiInterface
     */
    recipientsControllerUpdate(requestParameters: RecipientsApiRecipientsControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecipientCreatedResponseDto>;

}

/**
 * Request parameters for recipientsControllerCreate operation in RecipientsApi.
 * @export
 * @interface RecipientsApiRecipientsControllerCreateRequest
 */
export interface RecipientsApiRecipientsControllerCreateRequest {
    /**
     * Data to create a new recipient.
     * @type {CreateRecipientDto}
     * @memberof RecipientsApiRecipientsControllerCreate
     */
    readonly createRecipientDto: CreateRecipientDto
}

/**
 * Request parameters for recipientsControllerFindOne operation in RecipientsApi.
 * @export
 * @interface RecipientsApiRecipientsControllerFindOneRequest
 */
export interface RecipientsApiRecipientsControllerFindOneRequest {
    /**
     * Recipient ID
     * @type {string}
     * @memberof RecipientsApiRecipientsControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for recipientsControllerRemove operation in RecipientsApi.
 * @export
 * @interface RecipientsApiRecipientsControllerRemoveRequest
 */
export interface RecipientsApiRecipientsControllerRemoveRequest {
    /**
     * Recipient ID
     * @type {string}
     * @memberof RecipientsApiRecipientsControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for recipientsControllerUpdate operation in RecipientsApi.
 * @export
 * @interface RecipientsApiRecipientsControllerUpdateRequest
 */
export interface RecipientsApiRecipientsControllerUpdateRequest {
    /**
     * ID of the recipient to update
     * @type {string}
     * @memberof RecipientsApiRecipientsControllerUpdate
     */
    readonly id: string

    /**
     * New data for the recipient.
     * @type {UpdateRecipientDto}
     * @memberof RecipientsApiRecipientsControllerUpdate
     */
    readonly updateRecipientDto: UpdateRecipientDto
}

/**
 * RecipientsApi - object-oriented interface
 * @export
 * @class RecipientsApi
 * @extends {BaseAPI}
 */
export class RecipientsApi extends BaseAPI implements RecipientsApiInterface {
    /**
     * 
     * @summary Create a new recipient
     * @param {RecipientsApiRecipientsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientsApi
     */
    public recipientsControllerCreate(requestParameters: RecipientsApiRecipientsControllerCreateRequest, options?: RawAxiosRequestConfig) {
        return RecipientsApiFp(this.configuration).recipientsControllerCreate(requestParameters.createRecipientDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all recipients
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientsApi
     */
    public recipientsControllerFindAll(options?: RawAxiosRequestConfig) {
        return RecipientsApiFp(this.configuration).recipientsControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a single recipient
     * @param {RecipientsApiRecipientsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientsApi
     */
    public recipientsControllerFindOne(requestParameters: RecipientsApiRecipientsControllerFindOneRequest, options?: RawAxiosRequestConfig) {
        return RecipientsApiFp(this.configuration).recipientsControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a recipient by its ID
     * @param {RecipientsApiRecipientsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientsApi
     */
    public recipientsControllerRemove(requestParameters: RecipientsApiRecipientsControllerRemoveRequest, options?: RawAxiosRequestConfig) {
        return RecipientsApiFp(this.configuration).recipientsControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a recipient
     * @param {RecipientsApiRecipientsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientsApi
     */
    public recipientsControllerUpdate(requestParameters: RecipientsApiRecipientsControllerUpdateRequest, options?: RawAxiosRequestConfig) {
        return RecipientsApiFp(this.configuration).recipientsControllerUpdate(requestParameters.id, requestParameters.updateRecipientDto, options).then((request) => request(this.axios, this.basePath));
    }
}

