/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ImpactReportResponseDto } from '../models';
// @ts-ignore
import type { PartnerResponseDto } from '../models';
// @ts-ignore
import type { RetailerDashboardResponseDto } from '../models';
/**
 * RetailerPortalApi - axios parameter creator
 * @export
 */
export const RetailerPortalApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get the retailer home dashboard
         * @param {string} [locationId] Branch to report on. Defaults to the primary branch.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retailerPortalControllerFindDashboard: async (locationId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/retailer/dashboard`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (locationId !== undefined) {
                localVarQueryParameter['locationId'] = locationId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a branch\'s period impact report
         * @param {string} locationId Location ID
         * @param {string} [period] Period as &#x60;YYYY&#x60; or &#x60;YYYY-MM&#x60;. Defaults to the current year.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retailerPortalControllerFindImpact: async (locationId: string, period?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'locationId' is not null or undefined
            assertParamExists('retailerPortalControllerFindImpact', 'locationId', locationId)
            const localVarPath = `/api/retailer/locations/{locationId}/impact`
                .replace(`{${"locationId"}}`, encodeURIComponent(String(locationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a branch\'s donation partners
         * @param {string} locationId Location ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retailerPortalControllerFindPartners: async (locationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'locationId' is not null or undefined
            assertParamExists('retailerPortalControllerFindPartners', 'locationId', locationId)
            const localVarPath = `/api/retailer/locations/{locationId}/partners`
                .replace(`{${"locationId"}}`, encodeURIComponent(String(locationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RetailerPortalApi - functional programming interface
 * @export
 */
export const RetailerPortalApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RetailerPortalApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get the retailer home dashboard
         * @param {string} [locationId] Branch to report on. Defaults to the primary branch.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retailerPortalControllerFindDashboard(locationId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RetailerDashboardResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retailerPortalControllerFindDashboard(locationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RetailerPortalApi.retailerPortalControllerFindDashboard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a branch\'s period impact report
         * @param {string} locationId Location ID
         * @param {string} [period] Period as &#x60;YYYY&#x60; or &#x60;YYYY-MM&#x60;. Defaults to the current year.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retailerPortalControllerFindImpact(locationId: string, period?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImpactReportResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retailerPortalControllerFindImpact(locationId, period, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RetailerPortalApi.retailerPortalControllerFindImpact']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a branch\'s donation partners
         * @param {string} locationId Location ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retailerPortalControllerFindPartners(locationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PartnerResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retailerPortalControllerFindPartners(locationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RetailerPortalApi.retailerPortalControllerFindPartners']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RetailerPortalApi - factory interface
 * @export
 */
export const RetailerPortalApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RetailerPortalApiFp(configuration)
    return {
        /**
         * 
         * @summary Get the retailer home dashboard
         * @param {RetailerPortalApiRetailerPortalControllerFindDashboardRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retailerPortalControllerFindDashboard(requestParameters: RetailerPortalApiRetailerPortalControllerFindDashboardRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<RetailerDashboardResponseDto> {
            return localVarFp.retailerPortalControllerFindDashboard(requestParameters.locationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a branch\'s period impact report
         * @param {RetailerPortalApiRetailerPortalControllerFindImpactRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retailerPortalControllerFindImpact(requestParameters: RetailerPortalApiRetailerPortalControllerFindImpactRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImpactReportResponseDto> {
            return localVarFp.retailerPortalControllerFindImpact(requestParameters.locationId, requestParameters.period, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a branch\'s donation partners
         * @param {RetailerPortalApiRetailerPortalControllerFindPartnersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retailerPortalControllerFindPartners(requestParameters: RetailerPortalApiRetailerPortalControllerFindPartnersRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<PartnerResponseDto>> {
            return localVarFp.retailerPortalControllerFindPartners(requestParameters.locationId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RetailerPortalApi - interface
 * @export
 * @interface RetailerPortalApi
 */
export interface RetailerPortalApiInterface {
    /**
     * 
     * @summary Get the retailer home dashboard
     * @param {RetailerPortalApiRetailerPortalControllerFindDashboardRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RetailerPortalApiInterface
     */
    retailerPortalControllerFindDashboard(requestParameters?: RetailerPortalApiRetailerPortalControllerFindDashboardRequest, options?: RawAxiosRequestConfig): AxiosPromise<RetailerDashboardResponseDto>;

    /**
     * 
     * @summary Get a branch\'s period impact report
     * @param {RetailerPortalApiRetailerPortalControllerFindImpactRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RetailerPortalApiInterface
     */
    retailerPortalControllerFindImpact(requestParameters: RetailerPortalApiRetailerPortalControllerFindImpactRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImpactReportResponseDto>;

    /**
     * 
     * @summary Get a branch\'s donation partners
     * @param {RetailerPortalApiRetailerPortalControllerFindPartnersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RetailerPortalApiInterface
     */
    retailerPortalControllerFindPartners(requestParameters: RetailerPortalApiRetailerPortalControllerFindPartnersRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<PartnerResponseDto>>;

}

/**
 * Request parameters for retailerPortalControllerFindDashboard operation in RetailerPortalApi.
 * @export
 * @interface RetailerPortalApiRetailerPortalControllerFindDashboardRequest
 */
export interface RetailerPortalApiRetailerPortalControllerFindDashboardRequest {
    /**
     * Branch to report on. Defaults to the primary branch.
     * @type {string}
     * @memberof RetailerPortalApiRetailerPortalControllerFindDashboard
     */
    readonly locationId?: string
}

/**
 * Request parameters for retailerPortalControllerFindImpact operation in RetailerPortalApi.
 * @export
 * @interface RetailerPortalApiRetailerPortalControllerFindImpactRequest
 */
export interface RetailerPortalApiRetailerPortalControllerFindImpactRequest {
    /**
     * Location ID
     * @type {string}
     * @memberof RetailerPortalApiRetailerPortalControllerFindImpact
     */
    readonly locationId: string

    /**
     * Period as &#x60;YYYY&#x60; or &#x60;YYYY-MM&#x60;. Defaults to the current year.
     * @type {string}
     * @memberof RetailerPortalApiRetailerPortalControllerFindImpact
     */
    readonly period?: string
}

/**
 * Request parameters for retailerPortalControllerFindPartners operation in RetailerPortalApi.
 * @export
 * @interface RetailerPortalApiRetailerPortalControllerFindPartnersRequest
 */
export interface RetailerPortalApiRetailerPortalControllerFindPartnersRequest {
    /**
     * Location ID
     * @type {string}
     * @memberof RetailerPortalApiRetailerPortalControllerFindPartners
     */
    readonly locationId: string
}

/**
 * RetailerPortalApi - object-oriented interface
 * @export
 * @class RetailerPortalApi
 * @extends {BaseAPI}
 */
export class RetailerPortalApi extends BaseAPI implements RetailerPortalApiInterface {
    /**
     * 
     * @summary Get the retailer home dashboard
     * @param {RetailerPortalApiRetailerPortalControllerFindDashboardRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RetailerPortalApi
     */
    public retailerPortalControllerFindDashboard(requestParameters: RetailerPortalApiRetailerPortalControllerFindDashboardRequest = {}, options?: RawAxiosRequestConfig) {
        return RetailerPortalApiFp(this.configuration).retailerPortalControllerFindDashboard(requestParameters.locationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a branch\'s period impact report
     * @param {RetailerPortalApiRetailerPortalControllerFindImpactRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RetailerPortalApi
     */
    public retailerPortalControllerFindImpact(requestParameters: RetailerPortalApiRetailerPortalControllerFindImpactRequest, options?: RawAxiosRequestConfig) {
        return RetailerPortalApiFp(this.configuration).retailerPortalControllerFindImpact(requestParameters.locationId, requestParameters.period, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a branch\'s donation partners
     * @param {RetailerPortalApiRetailerPortalControllerFindPartnersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RetailerPortalApi
     */
    public retailerPortalControllerFindPartners(requestParameters: RetailerPortalApiRetailerPortalControllerFindPartnersRequest, options?: RawAxiosRequestConfig) {
        return RetailerPortalApiFp(this.configuration).retailerPortalControllerFindPartners(requestParameters.locationId, options).then((request) => request(this.axios, this.basePath));
    }
}

