/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AcceptDonationDto
 */
export interface AcceptDonationDto {
    /**
     * Vehicle that will collect.
     * @type {string}
     * @memberof AcceptDonationDto
     */
    'recipientVehicleId'?: string;
    /**
     * Person who will collect. Supplies the driver name on the certificate.
     * @type {string}
     * @memberof AcceptDonationDto
     */
    'driverContactId'?: string;
    /**
     * Start of a collection window the recipient can actually make, if it differs from the one offered.
     * @type {string}
     * @memberof AcceptDonationDto
     */
    'pickupWindowStart'?: string;
    /**
     * End of that window.
     * @type {string}
     * @memberof AcceptDonationDto
     */
    'pickupWindowEnd'?: string;
}

