/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddLinesToOpenDonationDto
 */
export interface AddLinesToOpenDonationDto {
    /**
     * The branch staging the stock.
     * @type {string}
     * @memberof AddLinesToOpenDonationDto
     */
    'locationId': string;
    /**
     * The lots to stage.
     * @type {Array<string>}
     * @memberof AddLinesToOpenDonationDto
     */
    'inventoryItemIds': Array<string>;
    /**
     * Who to donate to. Omit to let the server pick the preferred active partner.
     * @type {string}
     * @memberof AddLinesToOpenDonationDto
     */
    'recipientId'?: string;
}

