/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConfirmDonationDto
 */
export interface ConfirmDonationDto {
    /**
     * Pickup token the recipient presented, as the scanned code or its PIN. Must be unconsumed, unexpired, and issued for this donation.
     * @type {string}
     * @memberof ConfirmDonationDto
     */
    'pickupTokenCode': string;
    /**
     * Who released the goods on the donating side. Falls back to the contact linked to the confirming login, then the branch contact, then the retailer contact.
     * @type {string}
     * @memberof ConfirmDonationDto
     */
    'authorizedByLabel'?: string;
    /**
     * Who signed for the goods on the receiving side. The driver need not be a platform user, so this is free text.
     * @type {string}
     * @memberof ConfirmDonationDto
     */
    'receivedByLabel'?: string;
}

