/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReservationSource } from './reservation-source';

/**
 * 
 * @export
 * @interface CreateReservationDto
 */
export interface CreateReservationDto {
    /**
     * The store being collected from.
     * @type {string}
     * @memberof CreateReservationDto
     */
    'locationId': string;
    /**
     * The lots being claimed. All must be listed and available.
     * @type {Array<string>}
     * @memberof CreateReservationDto
     */
    'inventoryItemIds': Array<string>;
    /**
     * The named slot to collect in. Give this or both window bounds.
     * @type {string}
     * @memberof CreateReservationDto
     */
    'pickupSlotId'?: string;
    /**
     * Start of an explicit collection window.
     * @type {string}
     * @memberof CreateReservationDto
     */
    'pickupWindowStart'?: string;
    /**
     * End of an explicit collection window.
     * @type {string}
     * @memberof CreateReservationDto
     */
    'pickupWindowEnd'?: string;
    /**
     * Which entry point the claim came from.
     * @type {ReservationSource}
     * @memberof CreateReservationDto
     */
    'source'?: ReservationSource;
    /**
     * Who will collect, when it is already known.
     * @type {string}
     * @memberof CreateReservationDto
     */
    'driverContactId'?: string;
    /**
     * Vehicle that will collect, when it is already known.
     * @type {string}
     * @memberof CreateReservationDto
     */
    'recipientVehicleId'?: string;
}



