/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateRecipientVehicleDto
 */
export interface CreateRecipientVehicleDto {
    /**
     * Owning recipient.
     * @type {string}
     * @memberof CreateRecipientVehicleDto
     */
    'recipientId': string;
    /**
     * Registration plate, printed on the donation certificate.
     * @type {string}
     * @memberof CreateRecipientVehicleDto
     */
    'plate': string;
    /**
     * Free-text description of the vehicle.
     * @type {string}
     * @memberof CreateRecipientVehicleDto
     */
    'description'?: string;
    /**
     * Whether the load space is refrigerated.
     * @type {boolean}
     * @memberof CreateRecipientVehicleDto
     */
    'isRefrigerated'?: boolean;
    /**
     * How much it can carry in one trip.
     * @type {number}
     * @memberof CreateRecipientVehicleDto
     */
    'capacityKg'?: number;
    /**
     * Set to false to retire the vehicle without deleting it.
     * @type {boolean}
     * @memberof CreateRecipientVehicleDto
     */
    'isActive'?: boolean;
}

