/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserRole } from './user-role';

/**
 * 
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     * Login email. Stored case-insensitively.
     * @type {string}
     * @memberof CreateUserDto
     */
    'email': string;
    /**
     * Plain-text password. Hashed before storage and never returned by the API.
     * @type {string}
     * @memberof CreateUserDto
     */
    'password': string;
    /**
     * Authorization role. Determines which profile must be linked: `RETAILER` requires `retailerId`, `RECIPIENT` requires `recipientId`, `ADMIN` requires neither.
     * @type {UserRole}
     * @memberof CreateUserDto
     */
    'role': UserRole;
    /**
     * Retailer to link. Required when `role` is `RETAILER`.
     * @type {string}
     * @memberof CreateUserDto
     */
    'retailerId'?: string;
    /**
     * Recipient to link. Required when `role` is `RECIPIENT`.
     * @type {string}
     * @memberof CreateUserDto
     */
    'recipientId'?: string;
}



