/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateImpactFactorDto
 */
export interface CreateImpactFactorDto {
    /**
     * Identifier for this set of factors.
     * @type {string}
     * @memberof CreateImpactFactorDto
     */
    'label': string;
    /**
     * Meals one kilogram of rescued food is reckoned to provide.
     * @type {number}
     * @memberof CreateImpactFactorDto
     */
    'mealsPerKg': number;
    /**
     * Kilograms of CO2 avoided per kilogram of rescued food.
     * @type {number}
     * @memberof CreateImpactFactorDto
     */
    'co2KgPerKg': number;
    /**
     * First day these factors apply.
     * @type {string}
     * @memberof CreateImpactFactorDto
     */
    'effectiveFrom': string;
    /**
     * Last day these factors apply. Omit while they are current.
     * @type {string}
     * @memberof CreateImpactFactorDto
     */
    'effectiveTo'?: string;
}

