/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateLocationPickupSlotDto
 */
export interface CreateLocationPickupSlotDto {
    /**
     * Branch offering the slot.
     * @type {string}
     * @memberof CreateLocationPickupSlotDto
     */
    'locationId': string;
    /**
     * What the slot is called to both sides.
     * @type {string}
     * @memberof CreateLocationPickupSlotDto
     */
    'label': string;
    /**
     * ISO weekday the slot applies to, 1 = Monday. Omit for daily.
     * @type {number}
     * @memberof CreateLocationPickupSlotDto
     */
    'weekday'?: number;
    /**
     * Opening time, local to the branch\'s timezone.
     * @type {string}
     * @memberof CreateLocationPickupSlotDto
     */
    'startTime': string;
    /**
     * Closing time, local to the branch\'s timezone.
     * @type {string}
     * @memberof CreateLocationPickupSlotDto
     */
    'endTime': string;
    /**
     * Whether the slot is currently offered.
     * @type {boolean}
     * @memberof CreateLocationPickupSlotDto
     */
    'isActive'?: boolean;
}

