/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InvalidTokenReason } from './invalid-token-reason';

/**
 * 
 * @export
 * @interface CreateInvalidTokenDto
 */
export interface CreateInvalidTokenDto {
    /**
     * The revoked token\'s `jti` claim. Must be unique.
     * @type {string}
     * @memberof CreateInvalidTokenDto
     */
    'jti': string;
    /**
     * Owner of the revoked token.
     * @type {string}
     * @memberof CreateInvalidTokenDto
     */
    'userId': string;
    /**
     * When the token naturally expires (the JWT `exp`).
     * @type {string}
     * @memberof CreateInvalidTokenDto
     */
    'expiresAt': string;
    /**
     * Why the token was revoked.
     * @type {InvalidTokenReason}
     * @memberof CreateInvalidTokenDto
     */
    'reason': InvalidTokenReason;
}



