/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PartnershipStatus } from './partnership-status';

/**
 * 
 * @export
 * @interface CreatePartnershipDto
 */
export interface CreatePartnershipDto {
    /**
     * Retailer side.
     * @type {string}
     * @memberof CreatePartnershipDto
     */
    'retailerId': string;
    /**
     * Recipient side.
     * @type {string}
     * @memberof CreatePartnershipDto
     */
    'recipientId': string;
    /**
     * State of the relationship.
     * @type {PartnershipStatus}
     * @memberof CreatePartnershipDto
     */
    'status'?: PartnershipStatus;
    /**
     * Marks the recipient offered to by default when a manager does not choose.
     * @type {boolean}
     * @memberof CreatePartnershipDto
     */
    'isPreferred'?: boolean;
    /**
     * When the partnership began.
     * @type {string}
     * @memberof CreatePartnershipDto
     */
    'startedAt'?: string;
}



