/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DonationReceiptCreatedResponseDto
 */
export interface DonationReceiptCreatedResponseDto {
    /**
     * Unique certificate ID.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'id': string;
    /**
     * Donation certified.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'donationId': string;
    /**
     * Certificate number.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'receiptNumber': string;
    /**
     * When the certificate was issued (ISO 8601).
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'issuedAt': string;
    /**
     * Donor legal name.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'retailerLegalName': string;
    /**
     * Donor tax identifier.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'retailerTaxId'?: string | null;
    /**
     * Branch name.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'locationLabel': string;
    /**
     * Branch code.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'locationCode'?: string | null;
    /**
     * Branch address.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'locationAddress': string;
    /**
     * Who authorised the handover.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'authorizedByName': string;
    /**
     * Recipient legal name.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'recipientLegalName': string;
    /**
     * Recipient tax identifier.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'recipientTaxId'?: string | null;
    /**
     * Who collected.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'driverName'?: string | null;
    /**
     * Plate of the collecting vehicle.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'vehiclePlate'?: string | null;
    /**
     * Who signed for the goods on the receiving side, as free text.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'receivedByLabel'?: string | null;
    /**
     * PIN of the pickup token that released the goods.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'handoverPin'?: string | null;
    /**
     * Number of lines certified.
     * @type {number}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'lineCount': number;
    /**
     * Total units certified.
     * @type {number}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'totalQuantity': number;
    /**
     * Total weight certified.
     * @type {number}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'totalWeightKg': number;
    /**
     * Total retail value certified.
     * @type {number}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'totalRetailValue'?: number | null;
    /**
     * Currency of the totals.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'currency': string;
    /**
     * Meals the donation is reckoned to provide.
     * @type {number}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'estimatedMeals'?: number | null;
    /**
     * Emissions avoided.
     * @type {number}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'co2AvoidedKg'?: number | null;
    /**
     * Which conversion factors produced the impact figures.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'impactFactorId'?: string | null;
    /**
     * Statute the certificate is issued under.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'legalReference'?: string | null;
    /**
     * The consumed pickup token, retained as evidence of handover.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'verificationCode'?: string | null;
    /**
     * When the record was created (ISO 8601).
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'createdAt': string;
    /**
     * Human-readable message describing the outcome.
     * @type {string}
     * @memberof DonationReceiptCreatedResponseDto
     */
    'message': string;
}

