/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CancellationReasonCode } from './cancellation-reason-code';
// May contain unused imports in some cases
// @ts-ignore
import type { DonationLineResponseDto } from './donation-line-response-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { DonationOrigin } from './donation-origin';
// May contain unused imports in some cases
// @ts-ignore
import type { DonationStatus } from './donation-status';

/**
 * 
 * @export
 * @interface DonationResponseDto
 */
export interface DonationResponseDto {
    /**
     * Unique donation ID.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'id': string;
    /**
     * Human-readable reference.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'code': string;
    /**
     * Donating retailer.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'retailerId': string;
    /**
     * Branch collected from.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'locationId': string;
    /**
     * Receiving recipient.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'recipientId': string;
    /**
     * Lifecycle state.
     * @type {DonationStatus}
     * @memberof DonationResponseDto
     */
    'status': DonationStatus;
    /**
     * Which side started it. A `RECIPIENT_CLAIM` skips the offer/accept exchange.
     * @type {DonationOrigin}
     * @memberof DonationResponseDto
     */
    'origin': DonationOrigin;
    /**
     * Vehicle that will collect.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'recipientVehicleId'?: string | null;
    /**
     * Person who will collect.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'driverContactId'?: string | null;
    /**
     * Retailer-side user who created it.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'createdByUserId'?: string | null;
    /**
     * When it was offered to the recipient (ISO 8601).
     * @type {string}
     * @memberof DonationResponseDto
     */
    'offeredAt'?: string | null;
    /**
     * Recipient-side user who accepted.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'acceptedByUserId'?: string | null;
    /**
     * When the recipient accepted (ISO 8601).
     * @type {string}
     * @memberof DonationResponseDto
     */
    'acceptedAt'?: string | null;
    /**
     * When the recipient declined (ISO 8601).
     * @type {string}
     * @memberof DonationResponseDto
     */
    'declinedAt'?: string | null;
    /**
     * Why the recipient declined.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'declineReason'?: string | null;
    /**
     * Start of the agreed collection window (ISO 8601).
     * @type {string}
     * @memberof DonationResponseDto
     */
    'pickupWindowStart'?: string | null;
    /**
     * End of the agreed collection window (ISO 8601).
     * @type {string}
     * @memberof DonationResponseDto
     */
    'pickupWindowEnd'?: string | null;
    /**
     * Named branch slot the window was reserved against.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'pickupSlotId'?: string | null;
    /**
     * Retailer-side user who confirmed the handover.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'confirmedByUserId'?: string | null;
    /**
     * When the handover completed (ISO 8601).
     * @type {string}
     * @memberof DonationResponseDto
     */
    'completedAt'?: string | null;
    /**
     * When it was called off (ISO 8601).
     * @type {string}
     * @memberof DonationResponseDto
     */
    'cancelledAt'?: string | null;
    /**
     * Why it was called off.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'cancellationReason'?: string | null;
    /**
     * Number of lines.
     * @type {number}
     * @memberof DonationResponseDto
     */
    'lineCount': number;
    /**
     * Total units across every line.
     * @type {number}
     * @memberof DonationResponseDto
     */
    'totalQuantity': number;
    /**
     * Total weight of every line.
     * @type {number}
     * @memberof DonationResponseDto
     */
    'totalWeightKg': number;
    /**
     * Total retail value of every line.
     * @type {number}
     * @memberof DonationResponseDto
     */
    'totalRetailValue': number;
    /**
     * Currency of the totals.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'currency': string;
    /**
     * Meals this donation represents. Pinned when the donation is claimed or delivered.
     * @type {number}
     * @memberof DonationResponseDto
     */
    'estimatedMeals'?: number | null;
    /**
     * CO₂-equivalent emissions avoided, in kilograms.
     * @type {number}
     * @memberof DonationResponseDto
     */
    'co2AvoidedKg'?: number | null;
    /**
     * The factor row the two figures above were computed from.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'impactFactorId'?: string | null;
    /**
     * Cancellation reason as a fixed code.
     * @type {CancellationReasonCode}
     * @memberof DonationResponseDto
     */
    'cancellationReasonCode'?: CancellationReasonCode | null;
    /**
     * User who cancelled, whichever side they belong to.
     * @type {string}
     * @memberof DonationResponseDto
     */
    'cancelledByUserId'?: string | null;
    /**
     * The lines, when they were loaded with the donation.
     * @type {Array<DonationLineResponseDto>}
     * @memberof DonationResponseDto
     */
    'lines'?: Array<DonationLineResponseDto>;
    /**
     * When the donation was created (ISO 8601).
     * @type {string}
     * @memberof DonationResponseDto
     */
    'createdAt': string;
    /**
     * When the donation was last modified (ISO 8601).
     * @type {string}
     * @memberof DonationResponseDto
     */
    'updatedAt': string;
}



