/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DonationResponseDto } from './donation-response-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PageMetaDto } from './page-meta-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginatedResponseDto } from './paginated-response-dto';

/**
 * @type DonationsControllerSearch200Response
 * @export
 */
export type DonationsControllerSearch200Response = PaginatedResponseDto;


