/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DonationVehicleDto
 */
export interface DonationVehicleDto {
    /**
     * The vehicle.
     * @type {string}
     * @memberof DonationVehicleDto
     */
    'id': string;
    /**
     * Registration plate.
     * @type {string}
     * @memberof DonationVehicleDto
     */
    'plate': string;
    /**
     * How the driver describes it, for recognising it on arrival.
     * @type {string}
     * @memberof DonationVehicleDto
     */
    'description'?: string | null;
    /**
     * Whether it is refrigerated.
     * @type {boolean}
     * @memberof DonationVehicleDto
     */
    'isRefrigerated': boolean;
}

