/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InvalidTokenReason } from './invalid-token-reason';

/**
 * 
 * @export
 * @interface InvalidTokenCreatedResponseDto
 */
export interface InvalidTokenCreatedResponseDto {
    /**
     * Unique denylist entry ID.
     * @type {string}
     * @memberof InvalidTokenCreatedResponseDto
     */
    'id': string;
    /**
     * The revoked token\'s `jti` claim.
     * @type {string}
     * @memberof InvalidTokenCreatedResponseDto
     */
    'jti': string;
    /**
     * Owner of the revoked token.
     * @type {string}
     * @memberof InvalidTokenCreatedResponseDto
     */
    'userId': string;
    /**
     * When the token naturally expires (ISO 8601).
     * @type {string}
     * @memberof InvalidTokenCreatedResponseDto
     */
    'expiresAt': string;
    /**
     * Why the token was revoked.
     * @type {InvalidTokenReason}
     * @memberof InvalidTokenCreatedResponseDto
     */
    'reason': InvalidTokenReason;
    /**
     * Whether the token is already past its expiry.
     * @type {boolean}
     * @memberof InvalidTokenCreatedResponseDto
     */
    'isExpired': boolean;
    /**
     * When the token was invalidated (ISO 8601).
     * @type {string}
     * @memberof InvalidTokenCreatedResponseDto
     */
    'createdAt': string;
    /**
     * When the entry was last modified (ISO 8601).
     * @type {string}
     * @memberof InvalidTokenCreatedResponseDto
     */
    'updatedAt': string;
    /**
     * Human-readable message describing the outcome.
     * @type {string}
     * @memberof InvalidTokenCreatedResponseDto
     */
    'message': string;
}



