/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductCategory } from './product-category';

/**
 * 
 * @export
 * @interface InventoryItemProductDto
 */
export interface InventoryItemProductDto {
    /**
     * The catalogue product.
     * @type {string}
     * @memberof InventoryItemProductDto
     */
    'id': string;
    /**
     * Product name.
     * @type {string}
     * @memberof InventoryItemProductDto
     */
    'name': string;
    /**
     * Brand.
     * @type {string}
     * @memberof InventoryItemProductDto
     */
    'brand'?: string | null;
    /**
     * Barcode.
     * @type {string}
     * @memberof InventoryItemProductDto
     */
    'barcode'?: string | null;
    /**
     * Category the lot is filtered and grouped by.
     * @type {ProductCategory}
     * @memberof InventoryItemProductDto
     */
    'category': ProductCategory;
    /**
     * Catalogue image, used when the lot has none of its own.
     * @type {string}
     * @memberof InventoryItemProductDto
     */
    'imageUrl'?: string | null;
}



