/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DonationReason } from './donation-reason';
// May contain unused imports in some cases
// @ts-ignore
import type { InventoryItemProductDto } from './inventory-item-product-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { InventoryItemStatus } from './inventory-item-status';
// May contain unused imports in some cases
// @ts-ignore
import type { SurplusUrgency } from './surplus-urgency';
// May contain unused imports in some cases
// @ts-ignore
import type { UnitOfMeasure } from './unit-of-measure';

/**
 * 
 * @export
 * @interface InventoryItemResponseDto
 */
export interface InventoryItemResponseDto {
    /**
     * Unique lot ID.
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'id': string;
    /**
     * Branch holding the stock.
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'locationId': string;
    /**
     * What the lot contains.
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'productId': string;
    /**
     * Catalogue details, present when the product relation was loaded.
     * @type {InventoryItemProductDto}
     * @memberof InventoryItemResponseDto
     */
    'product'?: InventoryItemProductDto | null;
    /**
     * The image to render: the lot’s own photo, falling back to the catalogue image.
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'displayImageUrl'?: string | null;
    /**
     * How much there is.
     * @type {number}
     * @memberof InventoryItemResponseDto
     */
    'quantity': number;
    /**
     * Unit the quantity is counted in.
     * @type {UnitOfMeasure}
     * @memberof InventoryItemResponseDto
     */
    'unit': UnitOfMeasure;
    /**
     * Weight of the whole lot.
     * @type {number}
     * @memberof InventoryItemResponseDto
     */
    'weightKg': number;
    /**
     * Retail value of the whole lot.
     * @type {number}
     * @memberof InventoryItemResponseDto
     */
    'retailValue'?: number | null;
    /**
     * Retail value of a single unit.
     * @type {number}
     * @memberof InventoryItemResponseDto
     */
    'unitPrice'?: number | null;
    /**
     * How the unit is named to staff.
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'unitLabel'?: string | null;
    /**
     * Photo of this lot, overriding the catalogue image.
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'imageUrl'?: string | null;
    /**
     * Currency of the retail value.
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'currency': string;
    /**
     * When the lot expires (ISO 8601).
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'expiresAt'?: string | null;
    /**
     * Hours until expiry, derived rather than stored. Negative once past, null when there is no expiry.
     * @type {number}
     * @memberof InventoryItemResponseDto
     */
    'hoursRemaining'?: number | null;
    /**
     * Whole days until expiry, derived. Negative once past, null when there is no expiry.
     * @type {number}
     * @memberof InventoryItemResponseDto
     */
    'daysRemaining'?: number | null;
    /**
     * How pressing the lot is, derived from the hours remaining. Null when there is no expiry.
     * @type {SurplusUrgency}
     * @memberof InventoryItemResponseDto
     */
    'urgency'?: SurplusUrgency | null;
    /**
     * Why the lot is donatable.
     * @type {DonationReason}
     * @memberof InventoryItemResponseDto
     */
    'reason': DonationReason;
    /**
     * Condition notes.
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'reasonDescription'?: string | null;
    /**
     * Lifecycle state.
     * @type {InventoryItemStatus}
     * @memberof InventoryItemResponseDto
     */
    'status': InventoryItemStatus;
    /**
     * Whether the lot is published to the surplus shelf.
     * @type {boolean}
     * @memberof InventoryItemResponseDto
     */
    'isListed': boolean;
    /**
     * Donation this lot is committed to.
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'donationId'?: string | null;
    /**
     * When the lot was logged (ISO 8601).
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'listedAt': string;
    /**
     * When the lot was added to a donation (ISO 8601).
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'queuedAt'?: string | null;
    /**
     * When the lot was created (ISO 8601).
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'createdAt': string;
    /**
     * When the lot was last modified (ISO 8601).
     * @type {string}
     * @memberof InventoryItemResponseDto
     */
    'updatedAt': string;
}



