/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LocationType } from './location-type';
// May contain unused imports in some cases
// @ts-ignore
import type { OpeningHoursDto } from './opening-hours-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PickupWindowDto } from './pickup-window-dto';

/**
 * 
 * @export
 * @interface LocationCreatedResponseDto
 */
export interface LocationCreatedResponseDto {
    /**
     * Unique location ID.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'id': string;
    /**
     * Owning retailer. Exactly one owner is set.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'retailerId'?: string | null;
    /**
     * Owning recipient. Exactly one owner is set.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'recipientId'?: string | null;
    /**
     * Human-readable name for the site.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'label': string;
    /**
     * Human-readable branch code.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'code'?: string | null;
    /**
     * What kind of site this is.
     * @type {LocationType}
     * @memberof LocationCreatedResponseDto
     */
    'type': LocationType;
    /**
     * How this branch describes itself.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'storeFormat'?: string | null;
    /**
     * Street address, first line.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'addressLine1': string;
    /**
     * Street address, second line.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'addressLine2'?: string | null;
    /**
     * City.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'city': string;
    /**
     * District or neighbourhood.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'neighborhood'?: string | null;
    /**
     * State, region or department.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'state'?: string | null;
    /**
     * Postal code.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'postalCode'?: string | null;
    /**
     * Country as an ISO 3166-1 alpha-2 code.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'countryCode': string;
    /**
     * Latitude in decimal degrees.
     * @type {number}
     * @memberof LocationCreatedResponseDto
     */
    'latitude'?: number | null;
    /**
     * Longitude in decimal degrees.
     * @type {number}
     * @memberof LocationCreatedResponseDto
     */
    'longitude'?: number | null;
    /**
     * IANA timezone of the site.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'timezone': string;
    /**
     * Public opening hours, by weekday.
     * @type {Array<OpeningHoursDto>}
     * @memberof LocationCreatedResponseDto
     */
    'openingHours'?: Array<OpeningHoursDto> | null;
    /**
     * Recurring collection availability, by weekday.
     * @type {Array<PickupWindowDto>}
     * @memberof LocationCreatedResponseDto
     */
    'pickupWindows'?: Array<PickupWindowDto> | null;
    /**
     * Arrival notes for a collecting driver.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'accessInstructions'?: string | null;
    /**
     * Whether the site has refrigerated storage.
     * @type {boolean}
     * @memberof LocationCreatedResponseDto
     */
    'hasColdStorage': boolean;
    /**
     * Whether the site has a freezer.
     * @type {boolean}
     * @memberof LocationCreatedResponseDto
     */
    'hasFreezer': boolean;
    /**
     * Direct line for the site, in E.164 format.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'phone'?: string | null;
    /**
     * Whether this is the main site.
     * @type {boolean}
     * @memberof LocationCreatedResponseDto
     */
    'isPrimary': boolean;
    /**
     * Whether the site is accepting collections.
     * @type {boolean}
     * @memberof LocationCreatedResponseDto
     */
    'isActive': boolean;
    /**
     * Owning organization name, present when the owner relation was loaded.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'ownerName'?: string | null;
    /**
     * Whether the owning organization is verified, when the owner was loaded.
     * @type {boolean}
     * @memberof LocationCreatedResponseDto
     */
    'ownerIsVerified'?: boolean | null;
    /**
     * Name of the site-level contact to ask for, when the contacts were loaded.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'managerName'?: string | null;
    /**
     * When the site joined the platform (ISO 8601). Same as creation, named for the profile screens.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'memberSince': string;
    /**
     * Today\'s collection windows, derived from the site\'s pickup slots when they were loaded.
     * @type {Array<string>}
     * @memberof LocationCreatedResponseDto
     */
    'pickupHoursToday': Array<string>;
    /**
     * When the location was created (ISO 8601).
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'createdAt': string;
    /**
     * When the location was last modified (ISO 8601).
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'updatedAt': string;
    /**
     * Human-readable message describing the outcome.
     * @type {string}
     * @memberof LocationCreatedResponseDto
     */
    'message': string;
}



