/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserResponseDto } from './user-response-dto';

/**
 * 
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
    /**
     * Signed access token. Send it as `Authorization: Bearer <token>`.
     * @type {string}
     * @memberof LoginResponseDto
     */
    'accessToken': string;
    /**
     * Scheme to use in the Authorization header.
     * @type {string}
     * @memberof LoginResponseDto
     */
    'tokenType': string;
    /**
     * When the access token expires (ISO 8601).
     * @type {string}
     * @memberof LoginResponseDto
     */
    'expiresAt': string;
    /**
     * The signed-in account.
     * @type {UserResponseDto}
     * @memberof LoginResponseDto
     */
    'user': UserResponseDto;
    /**
     * Human-readable message describing the outcome.
     * @type {string}
     * @memberof LoginResponseDto
     */
    'message': string;
}

