/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
    /**
     * Login email. Matched case-insensitively.
     * @type {string}
     * @memberof LoginDto
     */
    'email': string;
    /**
     * Account password.
     * @type {string}
     * @memberof LoginDto
     */
    'password': string;
}

