/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NextPickupDto
 */
export interface NextPickupDto {
    /**
     * The donation being collected.
     * @type {string}
     * @memberof NextPickupDto
     */
    'donationId': string;
    /**
     * Reference shown to both parties.
     * @type {string}
     * @memberof NextPickupDto
     */
    'code': string;
    /**
     * Who is collecting.
     * @type {string}
     * @memberof NextPickupDto
     */
    'recipientName': string;
    /**
     * Named contact on the collecting side.
     * @type {string}
     * @memberof NextPickupDto
     */
    'contactPerson'?: string | null;
    /**
     * Plate of the collecting vehicle.
     * @type {string}
     * @memberof NextPickupDto
     */
    'vehiclePlate'?: string | null;
    /**
     * Start of the agreed window (ISO 8601).
     * @type {string}
     * @memberof NextPickupDto
     */
    'pickupWindowStart'?: string | null;
    /**
     * End of the agreed window (ISO 8601).
     * @type {string}
     * @memberof NextPickupDto
     */
    'pickupWindowEnd'?: string | null;
    /**
     * Minutes until the window opens, negative once it has. Null without a window.
     * @type {number}
     * @memberof NextPickupDto
     */
    'minutesUntilWindow'?: number | null;
}

