/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OfferDonationDto
 */
export interface OfferDonationDto {
    /**
     * Start of the proposed collection window. Overrides whatever the draft carried.
     * @type {string}
     * @memberof OfferDonationDto
     */
    'pickupWindowStart'?: string;
    /**
     * End of the proposed collection window.
     * @type {string}
     * @memberof OfferDonationDto
     */
    'pickupWindowEnd'?: string;
}

