/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PartnerLocationResponseDto
 */
export interface PartnerLocationResponseDto {
    /**
     * The store.
     * @type {string}
     * @memberof PartnerLocationResponseDto
     */
    'locationId': string;
    /**
     * Store name.
     * @type {string}
     * @memberof PartnerLocationResponseDto
     */
    'label': string;
    /**
     * Retailer brand.
     * @type {string}
     * @memberof PartnerLocationResponseDto
     */
    'retailerName': string;
    /**
     * District or neighbourhood.
     * @type {string}
     * @memberof PartnerLocationResponseDto
     */
    'neighborhood'?: string | null;
    /**
     * Collections completed from this store.
     * @type {number}
     * @memberof PartnerLocationResponseDto
     */
    'pickupCount': number;
}

