/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PickupTokenResponseDto
 */
export interface PickupTokenResponseDto {
    /**
     * Unique token ID.
     * @type {string}
     * @memberof PickupTokenResponseDto
     */
    'id': string;
    /**
     * Donation this token releases.
     * @type {string}
     * @memberof PickupTokenResponseDto
     */
    'donationId': string;
    /**
     * What the QR code encodes.
     * @type {string}
     * @memberof PickupTokenResponseDto
     */
    'code': string;
    /**
     * The same credential as a human-keyable PIN, for when the QR will not scan.
     * @type {string}
     * @memberof PickupTokenResponseDto
     */
    'pin': string;
    /**
     * When the token stops being accepted (ISO 8601).
     * @type {string}
     * @memberof PickupTokenResponseDto
     */
    'expiresAt': string;
    /**
     * Whether the token can still be used.
     * @type {boolean}
     * @memberof PickupTokenResponseDto
     */
    'isUsable': boolean;
    /**
     * When it was scanned (ISO 8601). Null means unused.
     * @type {string}
     * @memberof PickupTokenResponseDto
     */
    'consumedAt'?: string | null;
    /**
     * When the token was issued (ISO 8601).
     * @type {string}
     * @memberof PickupTokenResponseDto
     */
    'createdAt': string;
}

