/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReadyToDonateDto
 */
export interface ReadyToDonateDto {
    /**
     * Lots staged across open donations.
     * @type {number}
     * @memberof ReadyToDonateDto
     */
    'lineCount': number;
    /**
     * Their combined weight.
     * @type {number}
     * @memberof ReadyToDonateDto
     */
    'totalWeightKg': number;
    /**
     * Meals that weight represents.
     * @type {number}
     * @memberof ReadyToDonateDto
     */
    'estimatedMeals': number;
}

