/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProfileStatus } from './profile-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RecipientType } from './recipient-type';
// May contain unused imports in some cases
// @ts-ignore
import type { UrgencyThreshold } from './urgency-threshold';

/**
 * 
 * @export
 * @interface RecipientResponseDto
 */
export interface RecipientResponseDto {
    /**
     * Unique recipient ID.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'id': string;
    /**
     * What kind of receiver this is.
     * @type {RecipientType}
     * @memberof RecipientResponseDto
     */
    'type': RecipientType;
    /**
     * Registered organization name.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'legalName'?: string | null;
    /**
     * Public name of the organization, or the person\'s name.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'displayName': string;
    /**
     * Abbreviated name.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'shortName'?: string | null;
    /**
     * Government tax identifier.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'taxId'?: string | null;
    /**
     * Charity or non-profit registration number.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'registrationCode'?: string | null;
    /**
     * Mission statement.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'mission'?: string | null;
    /**
     * Where they operate, as they describe it.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'serviceArea'?: string | null;
    /**
     * Public website.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'website'?: string | null;
    /**
     * Absolute URL of the logo.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'logoUrl'?: string | null;
    /**
     * Lifecycle status.
     * @type {ProfileStatus}
     * @memberof RecipientResponseDto
     */
    'status': ProfileStatus;
    /**
     * Whether an admin has verified this recipient.
     * @type {boolean}
     * @memberof RecipientResponseDto
     */
    'isVerified': boolean;
    /**
     * When the recipient was verified (ISO 8601).
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'verifiedAt'?: string | null;
    /**
     * ID of the admin who verified this recipient.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'verifiedById'?: string | null;
    /**
     * Food-handling certification number.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'foodHandlingCertificationNumber'?: string | null;
    /**
     * Certification expiry date.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'certificationExpiresAt'?: string | null;
    /**
     * When the platform terms were accepted (ISO 8601).
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'termsAcceptedAt'?: string | null;
    /**
     * Version of the terms accepted.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'termsVersion'?: string | null;
    /**
     * IANA timezone the organization works in.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'timezone': string;
    /**
     * How far they are willing to collect, in kilometres.
     * @type {number}
     * @memberof RecipientResponseDto
     */
    'alertRadiusKm': number;
    /**
     * Which surplus urgencies they want to hear about.
     * @type {UrgencyThreshold}
     * @memberof RecipientResponseDto
     */
    'urgencyThreshold': UrgencyThreshold;
    /**
     * Whether push notifications are enabled.
     * @type {boolean}
     * @memberof RecipientResponseDto
     */
    'pushNotificationsEnabled': boolean;
    /**
     * Initials of the display name, derived rather than stored, for avatar placeholders.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'initials': string;
    /**
     * When they joined the platform (ISO 8601). Same as creation.
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'memberSince': string;
    /**
     * When the recipient was created (ISO 8601).
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'createdAt': string;
    /**
     * When the recipient was last modified (ISO 8601).
     * @type {string}
     * @memberof RecipientResponseDto
     */
    'updatedAt': string;
}



