/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RecipientVehicleResponseDto
 */
export interface RecipientVehicleResponseDto {
    /**
     * Unique vehicle ID.
     * @type {string}
     * @memberof RecipientVehicleResponseDto
     */
    'id': string;
    /**
     * Owning recipient.
     * @type {string}
     * @memberof RecipientVehicleResponseDto
     */
    'recipientId': string;
    /**
     * Registration plate.
     * @type {string}
     * @memberof RecipientVehicleResponseDto
     */
    'plate': string;
    /**
     * Vehicle description.
     * @type {string}
     * @memberof RecipientVehicleResponseDto
     */
    'description'?: string | null;
    /**
     * Whether the load space is refrigerated.
     * @type {boolean}
     * @memberof RecipientVehicleResponseDto
     */
    'isRefrigerated': boolean;
    /**
     * How much it can carry in one trip.
     * @type {number}
     * @memberof RecipientVehicleResponseDto
     */
    'capacityKg'?: number | null;
    /**
     * Whether the vehicle is still in service.
     * @type {boolean}
     * @memberof RecipientVehicleResponseDto
     */
    'isActive': boolean;
    /**
     * When the vehicle was registered (ISO 8601).
     * @type {string}
     * @memberof RecipientVehicleResponseDto
     */
    'createdAt': string;
    /**
     * When the vehicle was last modified (ISO 8601).
     * @type {string}
     * @memberof RecipientVehicleResponseDto
     */
    'updatedAt': string;
}

