/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductCategory } from './product-category';
// May contain unused imports in some cases
// @ts-ignore
import type { UnitOfMeasure } from './unit-of-measure';

/**
 * 
 * @export
 * @interface UpdateProductDto
 */
export interface UpdateProductDto {
    /**
     * Owning retailer.
     * @type {string}
     * @memberof UpdateProductDto
     */
    'retailerId'?: string;
    /**
     * EAN-13 or GTIN-14 barcode. Unique per retailer. Omit for unbarcoded goods such as loose produce.
     * @type {string}
     * @memberof UpdateProductDto
     */
    'barcode'?: string;
    /**
     * Product name, as it appears to staff and on the certificate.
     * @type {string}
     * @memberof UpdateProductDto
     */
    'name'?: string;
    /**
     * Manufacturer brand.
     * @type {string}
     * @memberof UpdateProductDto
     */
    'brand'?: string;
    /**
     * Store department, kept separate from the brand.
     * @type {string}
     * @memberof UpdateProductDto
     */
    'defaultDepartment'?: string;
    /**
     * Department the product belongs to.
     * @type {ProductCategory}
     * @memberof UpdateProductDto
     */
    'category'?: ProductCategory;
    /**
     * Absolute URL of the product photo.
     * @type {string}
     * @memberof UpdateProductDto
     */
    'imageUrl'?: string;
    /**
     * Unit this product is normally counted in.
     * @type {UnitOfMeasure}
     * @memberof UpdateProductDto
     */
    'defaultUnit'?: UnitOfMeasure;
    /**
     * Average weight of one unit, used to suggest a lot weight when staff do not weigh it.
     * @type {number}
     * @memberof UpdateProductDto
     */
    'averageUnitWeightKg'?: number;
}



