/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DonationReason } from './donation-reason';
// May contain unused imports in some cases
// @ts-ignore
import type { UnitOfMeasure } from './unit-of-measure';

/**
 * 
 * @export
 * @interface UpdateInventoryItemDto
 */
export interface UpdateInventoryItemDto {
    /**
     * Branch holding the stock.
     * @type {string}
     * @memberof UpdateInventoryItemDto
     */
    'locationId'?: string;
    /**
     * What the lot contains.
     * @type {string}
     * @memberof UpdateInventoryItemDto
     */
    'productId'?: string;
    /**
     * How much there is, counted in `unit`.
     * @type {number}
     * @memberof UpdateInventoryItemDto
     */
    'quantity'?: number;
    /**
     * Unit the quantity is counted in.
     * @type {UnitOfMeasure}
     * @memberof UpdateInventoryItemDto
     */
    'unit'?: UnitOfMeasure;
    /**
     * Weight of the whole lot. Given rather than derived, because pack weights vary.
     * @type {number}
     * @memberof UpdateInventoryItemDto
     */
    'weightKg'?: number;
    /**
     * Retail value of the whole lot, not of one unit.
     * @type {number}
     * @memberof UpdateInventoryItemDto
     */
    'retailValue'?: number;
    /**
     * Retail value of a single unit.
     * @type {number}
     * @memberof UpdateInventoryItemDto
     */
    'unitPrice'?: number;
    /**
     * How the unit is named to staff. Display only; `unit` stays canonical for arithmetic.
     * @type {string}
     * @memberof UpdateInventoryItemDto
     */
    'unitLabel'?: string;
    /**
     * Photo of this lot, overriding the catalogue image when given.
     * @type {string}
     * @memberof UpdateInventoryItemDto
     */
    'imageUrl'?: string;
    /**
     * Publish the lot to the surplus shelf, where any active recipient in range can claim it.
     * @type {boolean}
     * @memberof UpdateInventoryItemDto
     */
    'isListed'?: boolean;
    /**
     * Currency of the retail value, as an ISO 4217 code.
     * @type {string}
     * @memberof UpdateInventoryItemDto
     */
    'currency'?: string;
    /**
     * When the lot expires. Omit for non-perishables. Urgency and hours remaining are derived from this.
     * @type {string}
     * @memberof UpdateInventoryItemDto
     */
    'expiresAt'?: string;
    /**
     * Why the lot is donatable rather than sellable.
     * @type {DonationReason}
     * @memberof UpdateInventoryItemDto
     */
    'reason'?: DonationReason;
    /**
     * Condition notes for the recipient, reproduced on the donation certificate.
     * @type {string}
     * @memberof UpdateInventoryItemDto
     */
    'reasonDescription'?: string;
}



