/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateDonationDto
 */
export interface UpdateDonationDto {
    /**
     * Donating retailer.
     * @type {string}
     * @memberof UpdateDonationDto
     */
    'retailerId'?: string;
    /**
     * Branch the stock is collected from.
     * @type {string}
     * @memberof UpdateDonationDto
     */
    'locationId'?: string;
    /**
     * Receiving recipient, chosen from the retailer\'s partners.
     * @type {string}
     * @memberof UpdateDonationDto
     */
    'recipientId'?: string;
    /**
     * Start of the proposed collection window, confirmed when the recipient accepts.
     * @type {string}
     * @memberof UpdateDonationDto
     */
    'pickupWindowStart'?: string;
    /**
     * End of the proposed collection window.
     * @type {string}
     * @memberof UpdateDonationDto
     */
    'pickupWindowEnd'?: string;
    /**
     * Stock lots to put in the donation straight away. Each becomes a line and is reserved.
     * @type {Array<string>}
     * @memberof UpdateDonationDto
     */
    'inventoryItemIds'?: Array<string>;
}

