/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactType } from './contact-type';

/**
 * 
 * @export
 * @interface UpdateContactDto
 */
export interface UpdateContactDto {
    /**
     * Owning retailer. Provide exactly one of `retailerId` / `recipientId`.
     * @type {string}
     * @memberof UpdateContactDto
     */
    'retailerId'?: string;
    /**
     * Owning recipient. Provide exactly one of `retailerId` / `recipientId`.
     * @type {string}
     * @memberof UpdateContactDto
     */
    'recipientId'?: string;
    /**
     * Full name of the person.
     * @type {string}
     * @memberof UpdateContactDto
     */
    'fullName'?: string;
    /**
     * Email address. Stored case-insensitively.
     * @type {string}
     * @memberof UpdateContactDto
     */
    'email'?: string;
    /**
     * Phone number in E.164 format.
     * @type {string}
     * @memberof UpdateContactDto
     */
    'phone'?: string;
    /**
     * Alternate phone number in E.164 format.
     * @type {string}
     * @memberof UpdateContactDto
     */
    'secondaryPhone'?: string;
    /**
     * Role inside the organization.
     * @type {string}
     * @memberof UpdateContactDto
     */
    'jobTitle'?: string;
    /**
     * Which function this contact covers.
     * @type {ContactType}
     * @memberof UpdateContactDto
     */
    'type'?: ContactType;
    /**
     * Marks the main contact for the owner. At most one per owner.
     * @type {boolean}
     * @memberof UpdateContactDto
     */
    'isPrimary'?: boolean;
    /**
     * Internal notes about reaching this person.
     * @type {string}
     * @memberof UpdateContactDto
     */
    'notes'?: string;
    /**
     * Login this person owns, when they have one. Gives a logged-in driver a name for the donation certificate.
     * @type {string}
     * @memberof UpdateContactDto
     */
    'userId'?: string;
    /**
     * Branch this person works at, for a site-level contact such as a store manager. Omit for an organization-wide contact.
     * @type {string}
     * @memberof UpdateContactDto
     */
    'locationId'?: string;
}



