/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UrgencyThreshold } from './urgency-threshold';

/**
 * 
 * @export
 * @interface UpdateNotificationPreferencesDto
 */
export interface UpdateNotificationPreferencesDto {
    /**
     * How far from their locations they will collect.
     * @type {number}
     * @memberof UpdateNotificationPreferencesDto
     */
    'alertRadiusKm'?: number;
    /**
     * Which urgencies are worth alerting them about.
     * @type {UrgencyThreshold}
     * @memberof UpdateNotificationPreferencesDto
     */
    'urgencyThreshold'?: UrgencyThreshold;
    /**
     * Whether to send push notifications.
     * @type {boolean}
     * @memberof UpdateNotificationPreferencesDto
     */
    'pushNotificationsEnabled'?: boolean;
}



