/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserRole } from './user-role';

/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * Unique user ID.
     * @type {string}
     * @memberof UserResponseDto
     */
    'id': string;
    /**
     * Login email.
     * @type {string}
     * @memberof UserResponseDto
     */
    'email': string;
    /**
     * Authorization role.
     * @type {UserRole}
     * @memberof UserResponseDto
     */
    'role': UserRole;
    /**
     * Linked retailer, when `role` is `RETAILER`.
     * @type {string}
     * @memberof UserResponseDto
     */
    'retailerId'?: string | null;
    /**
     * Linked recipient, when `role` is `RECIPIENT`.
     * @type {string}
     * @memberof UserResponseDto
     */
    'recipientId'?: string | null;
    /**
     * Whether the account may log in.
     * @type {boolean}
     * @memberof UserResponseDto
     */
    'isActive': boolean;
    /**
     * Whether the email has been confirmed.
     * @type {boolean}
     * @memberof UserResponseDto
     */
    'isEmailVerified': boolean;
    /**
     * When the email was confirmed (ISO 8601).
     * @type {string}
     * @memberof UserResponseDto
     */
    'emailVerifiedAt'?: string | null;
    /**
     * Last successful login (ISO 8601).
     * @type {string}
     * @memberof UserResponseDto
     */
    'lastLoginAt'?: string | null;
    /**
     * When the account was created (ISO 8601).
     * @type {string}
     * @memberof UserResponseDto
     */
    'createdAt': string;
    /**
     * When the account was last modified (ISO 8601).
     * @type {string}
     * @memberof UserResponseDto
     */
    'updatedAt': string;
}



