/* tslint:disable */
/* eslint-disable */
/**
 * Spira API Documentation
 * Spira API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VerifiedRecipientDto } from './verified-recipient-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { VerifiedSummaryDto } from './verified-summary-dto';

/**
 * 
 * @export
 * @interface VerifyPickupTokenResponseDto
 */
export interface VerifyPickupTokenResponseDto {
    /**
     * Whether the credential may be accepted.
     * @type {boolean}
     * @memberof VerifyPickupTokenResponseDto
     */
    'valid': boolean;
    /**
     * Why it was rejected. Null when valid.
     * @type {string}
     * @memberof VerifyPickupTokenResponseDto
     */
    'message'?: string | null;
    /**
     * The donation it releases. Null when invalid.
     * @type {string}
     * @memberof VerifyPickupTokenResponseDto
     */
    'donationId'?: string | null;
    /**
     * Reference shown to both parties. Null when invalid.
     * @type {string}
     * @memberof VerifyPickupTokenResponseDto
     */
    'code'?: string | null;
    /**
     * Who is collecting. Null when invalid.
     * @type {VerifiedRecipientDto}
     * @memberof VerifyPickupTokenResponseDto
     */
    'recipient'?: VerifiedRecipientDto | null;
    /**
     * What is being handed over. Null when invalid.
     * @type {VerifiedSummaryDto}
     * @memberof VerifyPickupTokenResponseDto
     */
    'summary'?: VerifiedSummaryDto | null;
}

